set(CTEST_PROJECT_NAME "baci")
set(CTEST_NIGHTLY_START_TIME "00:01:00 CEST")

set(CTEST_DROP_METHOD "http")

if (DEFINED ENV{CTEST_DROP_SITE_GITLAB})
    set(CTEST_DROP_SITE $ENV{CTEST_DROP_SITE_GITLAB})
else()
    set(CTEST_DROP_SITE "jacobi.lnm.mw.tum.de")
endif (DEFINED ENV{CTEST_DROP_SITE_GITLAB})

if (DEFINED ENV{CTEST_DROP_LOCATION_GITLAB})
    set(CTEST_DROP_LOCATION $ENV{CTEST_DROP_LOCATION_GITLAB})
else()
    set(CTEST_DROP_LOCATION "/cdash/submit.php?project=baci")
endif (DEFINED ENV{CTEST_DROP_LOCATION_GITLAB})

set(CTEST_DROP_SITE_CDASH TRUE)

