#!/bin/sh

BACI_HOME=`dirname $0`
EXTRA_ARGS=$@

MPIDIR=/cluster/openmpi-1.1.4
export PATH=/cluster/gcc-4.2.2/bin:$PATH:$MPIDIR/bin

/lnm/bin/cmake \
    -D CMAKE_EXE_LINKER_FLAGS:STRING="-lg2c" \
    -D CMAKE_Fortran_COMPILER:FILEPATH="/usr/bin/g77" \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
    -D QHULL:BOOL=OFF \
    -D D_ALE:BOOL=ON \
    -D D_BEAM2:BOOL=ON \
    -D D_BEAM2R:BOOL=ON \
    -D D_BEAM3:BOOL=ON \
    -D D_FLUID2:BOOL=ON \
    -D D_FLUID3:BOOL=ON \
    -D D_SHELL8:BOOL=ON \
    -D D_SOH8:BOOL=ON \
    -D D_SOLID3:BOOL=ON \
    -D D_SOTET:BOOL=ON \
    -D D_THERMO:BOOL=ON \
    -D D_TORSION2:BOOL=ON \
    -D D_TORSION3:BOOL=ON \
    -D D_TRUSS2:BOOL=ON \
    -D D_TRUSS3:BOOL=ON \
    -D D_WALL1:BOOL=ON \
    -D INCLUDE_INSTALL_DIR:FILEPATH="/lnm/include" \
    -D LIB_INSTALL_DIR:FILEPATH="/lnm/lib" \
    -D Trilinos_DIR:FILEPATH="/lnm/lib/Trilinos_dev_10022010/cluster_openmpi" \
    $EXTRA_ARGS \
    ${BACI_HOME}
