#!/bin/sh

BACI_HOME=`dirname $0`
EXTRA_ARGS=$@
BUILD_TYPE="RELEASE"

MPIDIR=/cluster/openmpi-1.1.4
export PATH=/cluster/gcc-4.2.2/bin:$PATH:$MPIDIR/bin

/lnm/bin/cmake \
    -D CMAKE_BUILD_TYPE:STRING=$BUILD_TYPE \
    -D CMAKE_SYSTEM_PREFIX_PATH:PATH="$MPIDIR" \
    -D CMAKE_CXX_COMPILER:FILEPATH="$MPIDIR/bin/mpic++" \
    -D CMAKE_C_COMPILER:FILEPATH="$MPIDIR/bin/mpicc" \
    -D CMAKE_CXX_FLAGS:STRING="-Wall -DSIXTYFOUR -ansi -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE" \
    -D CMAKE_CXX_FLAGS_RELEASE:STRING="-pipe -O3 -ffast-math -funroll-all-loops -fpeel-loops -ftracer -funswitch-loops -funit-at-a-time" \
    -D CMAKE_C_FLAGS:STRING="-Wall -DSIXTYFOUR -ansi -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE" \
    -D CMAKE_C_FLAGS_RELEASE:STRING="-pipe -O3 -ffast-math -funroll-all-loops -fpeel-loops -ftracer -funswitch-loops -funit-at-a-time" \
    -D CMAKE_EXE_LINKER_FLAGS:STRING="-Xlinker -defsym -Xlinker MAIN__=main" \
    -D CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING="-O2" \
    -D CMAKE_Fortran_COMPILER:FILEPATH="/usr/bin/g77" \
    -D CMAKE_Fortran_FLAGS:STRING="-Wall -DSIXTYFOUR -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE" \
    -D CMAKE_Fortran_FLAGS_RELEASE:STRING="-pipe -O5 -ffast-math -funroll-all-loops -fpeel-loops -ftracer -funswitch-loops -funit-at-a-time" \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
    -D TRAP_FE:BOOL=OFF \
    -D D_ALE:BOOL=ON \
    -D D_FLUID3:BOOL=ON \
    -D D_SOH8:BOOL=ON \
    -D D_SOTET:BOOL=ON \
    -D D_THERMO:BOOL=ON \
    -D INCLUDE_INSTALL_DIR:FILEPATH="/lnm/include" \
    -D LIB_INSTALL_DIR:FILEPATH="/lnm/lib" \
    -D Trilinos_DIR:FILEPATH="/lnm/lib/Trilinos_dev_10022010/cluster_openmpi" \
    -D BLAS_LIBRARIES:STRING="/lnm/lib/libacml_goto.a" \
    -D LAPACK_LIBRARIES:STRING="/lnm/lib/libacml_goto.a" \
    -D MPI_DIR:FILEPATH=$MPIDIR \
    $EXTRA_ARGS \
    ${BACI_HOME}

#    -D CMAKE_Fortran_COMPILER:FILEPATH="$MPIDIR/bin/mpif90" \
