#!/bin/sh

# ln -s /usr/lib/blitz/include/blitz/gnu /usr/include/blitz

BACI_HOME=`dirname $0`
EXTRA_ARGS=$@
BUILD_TYPE="DEBUG"

MPIDIR=/usr
INCLUDE_INSTALL_DIR="/lnm/lib/fc8/openmpi/include"
LIB_INSTALL_DIR="/lnm/lib/fc8/openmpi/lib"
#Trilinos_DIR="/lnm/lib/fc8/openmpi/trilinos"
Trilinos_DIR="/lnm/lib/Trilinos_dev_10022010/fc8_openmpi_trilinos_dbg"
#Trilinos_DIR="/lnm/lib/Trilinos_dev/fc8_openmpi_trilinos_dbg"

/lnm/programs/cmake-2.8.2/bin/cmake \
    -D CMAKE_BUILD_TYPE:STRING=$BUILD_TYPE \
    -D CMAKE_CXX_COMPILER:FILEPATH="$MPIDIR/bin/mpic++" \
    -D CMAKE_C_COMPILER:FILEPATH="$MPIDIR/bin/mpicc" \
    -D CMAKE_Fortran_COMPILER:FILEPATH="$MPIDIR/bin/mpif90" \
    -D CMAKE_CXX_FLAGS:STRING="-Wall -march=i686 -Wconversion -msse3 -mfpmath=sse -ansi -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE" \
    -D CMAKE_CXX_FLAGS_RELEASE:STRING="-O3" \
    -D CMAKE_C_FLAGS:STRING="-Wall -march=i686 -Wconversion -msse3 -mfpmath=sse -ansi -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE" \
    -D CMAKE_C_FLAGS_RELEASE:STRING="-O3" \
    -D CMAKE_EXE_LINKER_FLAGS:STRING="" \
    -D CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING="-O2" \
    -D CMAKE_Fortran_FLAGS:STRING="-Wall -march=i686 -msse3 -mfpmath=sse -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE" \
    -D CMAKE_Fortran_FLAGS_RELEASE:STRING="-O5 -funroll-all-loops -malign-double" \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
    -D DEBUG:BOOL=ON \
    -D TRAP_FE:BOOL=OFF \
    -D PARALLEL:BOOL=ON \
    -D PARMETIS:BOOL=ON \
    -D COLOROUTPUT=ON \
    -D QHULL:BOOL=ON \
    -D D_EXODUS:BOOL=ON \
    -D D_ALE:BOOL=ON \
    -D D_BEAM2:BOOL=ON \
    -D D_BEAM2R:BOOL=ON \
    -D D_BEAM3:BOOL=ON \
    -D D_BEAM3II:BOOL=ON \
    -D D_FLUID3:BOOL=ON \
    -D D_SHELL8:BOOL=ON \
    -D D_SOH8:BOOL=ON \
    -D D_SOLID3:BOOL=ON \
    -D D_SOTET:BOOL=ON \
    -D D_THERMO:BOOL=ON \
    -D D_TORSION2:BOOL=ON \
    -D D_TORSION3:BOOL=ON \
    -D D_TRUSS2:BOOL=ON \
    -D D_TRUSS3:BOOL=ON \
    -D D_WALL1:BOOL=ON \
    -D INCLUDE_INSTALL_DIR:FILEPATH=$INCLUDE_INSTALL_DIR \
    -D LIB_INSTALL_DIR:FILEPATH=$LIB_INSTALL_DIR \
    -D Trilinos_DIR:FILEPATH=$Trilinos_DIR \
    $EXTRA_ARGS \
    ${BACI_HOME}

cd $BACI_HOME
if [ -f .cproject ]; then ./adapt_cproject.py `basename $0`; fi
