#!/bin/sh

# ln -s /usr/lib/blitz/include/blitz/gnu /usr/include/blitz

BACI_HOME=`dirname $0`
EXTRA_ARGS=$@
BUILD_TYPE="RELEASE"

INCLUDE_INSTALL_DIR="/lnm/lib/fc8/openmpi/include"
LIB_INSTALL_DIR="/lnm/lib/fc8/openmpi/lib"
Trilinos_DIR="/lnm/lib/fc8/openmpi/trilinos"

/lnm/programs/cmake-2.8.0/bin/cmake \
    -D CMAKE_BUILD_TYPE:STRING=$BUILD_TYPE \
    -D CMAKE_CXX_FLAGS:STRING="-Wall -march=i686 -Wconversion -msse3 -mfpmath=sse -ansi -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE" \
    -D CMAKE_CXX_FLAGS_RELEASE:STRING="-O3" \
    -D CMAKE_C_FLAGS:STRING="-Wall -march=i686 -Wconversion -msse3 -mfpmath=sse -ansi -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE" \
    -D CMAKE_C_FLAGS_RELEASE:STRING="-O3" \
    -D CMAKE_EXE_LINKER_FLAGS:STRING="" \
    -D CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING="-O2" \
    -D CMAKE_Fortran_FLAGS:STRING="-Wall -march=i686 -msse3 -mfpmath=sse -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE" \
    -D CMAKE_Fortran_FLAGS_RELEASE:STRING="-O5 -funroll-all-loops -malign-double" \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
    -D DEBUG:BOOL=OFF \
    -D D_EXODUS:BOOL=ON \
    -D D_ALE:BOOL=ON \
    -D D_ALE:BOOL=ON \
    -D D_BEAM2:BOOL=ON \
    -D D_BEAM2R:BOOL=ON \
    -D D_BEAM3:BOOL=ON \
    -D D_BEAM3II:BOOL=ON \
    -D D_FLUID2:BOOL=ON \
    -D D_FLUID3:BOOL=ON \
    -D D_SHELL8:BOOL=ON \
    -D D_SOH8:BOOL=ON \
    -D D_SOLID3:BOOL=ON \
    -D D_SOTET:BOOL=ON \
    -D D_THERMO:BOOL=ON \
    -D D_TORSION2:BOOL=ON \
    -D D_TORSION3:BOOL=ON \
    -D D_TRUSS2:BOOL=ON \
    -D D_TRUSS3:BOOL=ON \
    -D D_WALL1:BOOL=ON \
    -D INCLUDE_INSTALL_DIR:FILEPATH=$INCLUDE_INSTALL_DIR \
    -D LIB_INSTALL_DIR:FILEPATH=$LIB_INSTALL_DIR \
    -D Trilinos_DIR:FILEPATH=$Trilinos_DIR \
    $EXTRA_ARGS \
    ${BACI_HOME}

./adapt_cproject.py `basename $0`