#!/bin/sh

# ln -s /usr/lib/blitz/include/blitz/gnu /usr/include/blitz

BACI_HOME=`dirname $0`
EXTRA_ARGS=$@
BUILD_TYPE="RELEASE"

##############################################################
# read in cmake version
LOCAL_CMAKE_VERSION=`cmake --version`

if [ "$LOCAL_CMAKE_VERSION" == "cmake version 2.8.0" ]; then
	echo "Detected cmake (" $LOCAL_CMAKE_VERSION ") -> Fedora Core 12"
	OS_VERSION="FC12"
	CMAKE_COMMAND=cmake
else
	echo "Local cmake outdated (" $LOCAL_CMAKE_VERSION ") -> Fedora Core 8"
	OS_VERSION="FC8"
	CMAKE_COMMAND=/lnm/programs/cmake-2.8.2/bin/cmake
fi

# remove CMakeCache.txt
rm -f CMakeCache.txt

############################################################
# decide which MPI is used
if [ "$OS_VERSION" == "FC8" ]; then
	MPIDIR=/usr
elif [ "$OS_VERSION" == "FC12" ]; then
	MPIDIR=/usr/lib/openmpi
else
	echo "unknown OS version! This is fatal!"
	exit
fi

############################################################
# use LNM Trilinos Q1/2012 (d)
INCLUDE_INSTALL_DIR="/lnm/lib/Q1_2012/fc8/openmpi-gcc/include"
LIB_INSTALL_DIR="/lnm/lib/Q1_2012/fc8/openmpi-gcc/lib"
Trilinos_PREFIX="/lnm/lib/Q1_2012/trilinos/fc8_openmpi_release/lib/cmake/Trilinos"
Trilinos_DIR="/lnm/lib/Q1_2012/trilinos"

############################################################
# use LNM Trilinos Q4/2011 (a)
#INCLUDE_INSTALL_DIR="/lnm/lib/Q4_2011/fc8/openmpi-gcc/include"
#LIB_INSTALL_DIR="/lnm/lib/Q4_2011/fc8/openmpi-gcc/lib"
#Trilinos_PREFIX="/lnm/lib/Q4_2011/fc8/openmpi-gcc/trilinos"


$CMAKE_COMMAND \
    -D CMAKE_BUILD_TYPE:STRING=$BUILD_TYPE \
    -D CMAKE_CXX_COMPILER:FILEPATH="$MPIDIR/bin/mpic++" \
    -D CMAKE_C_COMPILER:FILEPATH="$MPIDIR/bin/mpicc" \
    -D CMAKE_Fortran_COMPILER:FILEPATH="$MPIDIR/bin/mpif90" \
    -D CMAKE_CXX_FLAGS:STRING="-Wall -march=i686 -Wconversion -msse3 -mfpmath=sse -ansi -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE" \
    -D CMAKE_CXX_FLAGS_RELEASE:STRING="-O3" \
    -D CMAKE_C_FLAGS:STRING="-Wall -march=i686 -Wconversion -msse3 -mfpmath=sse -ansi -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE" \
    -D CMAKE_C_FLAGS_RELEASE:STRING="-O3" \
    -D CMAKE_EXE_LINKER_FLAGS:STRING="" \
    -D CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING="-O2" \
    -D CMAKE_Fortran_FLAGS:STRING="-Wall -march=i686 -msse3 -mfpmath=sse -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE" \
    -D CMAKE_Fortran_FLAGS_RELEASE:STRING="-O5 -funroll-all-loops -malign-double" \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
    -D HAVENOT_SUPERLU:BOOL=OFF \
    -D HAVE_TEKO:BOOL=ON \
    -D HAVE_MueLu:BOOL=OFF \
    -D TRILINOS_DEV:BOOL=ON \
    -D D_ARTNET:BOOL=ON \
    -D D_RED_AIRWAYS:BOOL=ON \
    -D TRAP_FE:BOOL=OFF \
    -D PARALLEL:BOOL=ON \
    -D PARMETIS:BOOL=ON \
    -D COLOROUTPUT:BOOL=ON \
    -D D_EXODUS:BOOL=ON \
    -D D_ALE:BOOL=ON \
    -D D_BEAM2:BOOL=ON \
    -D D_BEAM2R:BOOL=ON \
    -D D_BEAM3:BOOL=ON \
    -D D_BEAM3II:BOOL=ON \
    -D D_FLUID3:BOOL=ON \
    -D D_SHELL8:BOOL=ON \
    -D D_SOH8:BOOL=ON \
    -D D_SOLID3:BOOL=ON \
    -D D_SOTET:BOOL=ON \
    -D D_THERMO:BOOL=ON \
    -D D_TORSION2:BOOL=ON \
    -D D_TORSION3:BOOL=ON \
    -D D_TRUSS2:BOOL=ON \
    -D D_TRUSS3:BOOL=ON \
    -D D_WALL1:BOOL=ON \
    -D INCLUDE_INSTALL_DIR:FILEPATH=$INCLUDE_INSTALL_DIR \
    -D LIB_INSTALL_DIR:FILEPATH=$LIB_INSTALL_DIR \
    -D Trilinos_DIR:FILEPATH=$Trilinos_PREFIX \
    -D BOOST_INCLUDEDIR:FILEPATH=$INCLUDE_INSTALL_DIR \
    -D BOOST_LIBRARYDIR:FILEPATH=$LIB_INSTALL_DIR \
    -D QHULL_LIBRARY_DIR:FILEPATH=$LIB_INSTALL_DIR \
    -D QHULL_INCLUDE_DIR:FILEPATH=$INCLUDE_INSTALL_DIR \
    -D MPI_DIR:FILEPATH=$MPIDIR \
    $EXTRA_ARGS \
    ${BACI_HOME}

cd $BACI_HOME
if [ -f .cproject ]; then ./adapt_cproject.py `basename $0`; fi

