#!/bin/sh
#
# CCARAT Configuration
# 
# Create a Makefile with dependency information for a user supplied configuration file.
#

# some usability tests
if [ "x$1" = "x" -o "x$2" = "x" -o "x$3" = "x" ]; then
  echo usage: $0 ccarat-input-file config-file-name defines-file-name
  exit 1
fi

if [ ! -s "$1" ]; then
  echo $0: file not found: $1
  exit 1
fi

if [ ! -r "$1" ]; then
  echo $0: file not readable: $1
  exit 1
fi

if [ ! -s "$2" ]; then
  echo $0: file not found: $2
  exit 1
fi

if [ ! -r "$2" ]; then
  echo $0: file not readable: $2
  exit 1
fi

makefile="Makefile"
inputfile="$1"
configfile="$2"
definefile="$3"
specialargs="$4"

. ./scripts/extract-defines.sh

if [ "x$DEBUG" = "xyes" ] ; then
  echo "DEBUG" >> "$definefile"
fi

. ./scripts/setup-variables.sh
. ./scripts/setup-libraries.sh
. ./scripts/setup-objects.sh
. ./scripts/build-makefile.sh
