#--------------------------------------------------------------------
# enter path to the individual source directory
#--------------------------------------------------------------------
#SRC       = /bau/statik/<USER>/wdir/ccarat/src
