#
# binaries
#               main
OBJS_MAIN     = src/global_full/main_ccarat.o
#               global_full
OBJS_GLOBAL   = src/global_full/global_control.o \
                src/global_full/global_cal_control.o
OBJS_GLOBAL_CPP =
#               structure
OBJS_STRUCTURE= 
#               solver
OBJS_SOLVER   = 
#               solver (c++)
OBJS_SOLVER_CPP = 
#               discretization (c++)
OBJS_DRT_LIB  = src/drt_lib/drt_discret.o \
                src/drt_lib/drt_discret_fillcomplete.o \
                src/drt_lib/drt_discret_conditions.o \
                src/drt_lib/drt_discret_partition.o \
                src/drt_lib/drt_discret_utils.o \
                src/drt_lib/drt_globalproblem.o \
                src/drt_lib/drt_inputreader.o \
                src/drt_lib/drt_elementreader.o \
                src/drt_lib/drt_nodereader.o \
                src/drt_lib/drt_element.o \
                src/drt_lib/drt_elementregister.o \
                src/drt_lib/drt_node.o \
                src/drt_lib/drt_container.o \
                src/drt_lib/drt_condition.o \
                src/drt_lib/drt_condition_utils.o \
                src/drt_lib/drt_condition_selector.o \
                src/drt_lib/drt_conditiondefinition.o \
                src/drt_lib/drt_materialdefinition.o \
                src/drt_lib/drt_dofset.o \
                src/drt_lib/drt_dofset_base.o \
                src/drt_lib/drt_dofset_proxy.o \
                src/drt_lib/drt_linedefinition.o \
                src/drt_lib/drt_elementdefinition.o \
                src/drt_lib/drt_resulttest.o \
                src/drt_fem_general/drt_utils_integration.o \
                src/drt_fem_general/drt_utils_dgfem_basisfunctions.o \
                src/drt_fem_general/drt_utils_fem_shapefunctions.o \
                src/drt_fem_general/drt_utils_boundary_integration.o \
                src/drt_fem_general/drt_utils_local_connectivity_matrices.o \
                src/drt_lib/drt_utils.o \
                src/drt_lib/drt_utils_parmetis.o \
                src/drt_lib/drt_utils_metis.o \
                src/drt_lib/drt_utils_createdis.o \
                src/drt_lib/drt_parobject.o \
                src/drt_lib/drt_exporter.o \
                src/drt_lib/drt_dserror.o \
                src/drt_lib/linalg_utils.o \
                src/drt_lib/linalg_serialdensematrix.o \
                src/drt_lib/linalg_serialdensevector.o \
                src/drt_lib/drt_nodematchingoctree.o \
                src/drt_lib/drt_parser.o \
                src/drt_lib/drt_timecurve.o \
                src/drt_lib/drt_function.o \
                src/drt_lib/drt_discret_evaluate.o \
                src/drt_lib/linalg_mapextractor.o \
                src/drt_lib/linalg_sparsematrix.o \
                src/drt_lib/linalg_blocksparsematrix.o \
                src/drt_fluid/drt_pbcdofset.o \
                src/drt_fluid/drt_periodicbc.o \
                src/drt_fluid/fluid_rotsym_periodicbc_utils.o \
                src/drt_geometry/position_array.o \
                src/drt_geometry/searchtree_nearestobject.o \
                src/drt_geometry/searchtree_geometry_service.o \
                src/drt_geometry/searchtree.o \
                src/drt_geometry/intersection_interfacepoint.o \
                src/drt_geometry/intersection_math.o \
                src/drt_geometry/intersection_service.o \
                src/drt_geometry/intersection.o \
                src/drt_geometry/integrationcell.o \
                src/drt_lib/drt_locsys.o
#               input parameters and definitions
OBJS_DRT_INPAR = \
                src/drt_inpar/drt_validparameters.o \
                src/drt_inpar/drt_validconditions.o \
                src/drt_inpar/drt_validmaterials.o \
                src/drt_inpar/drt_boolifyparameters.o
#               nurbs discretization for isogeometric fe (c++)
OBJS_DRT_NURBS_DISCRET_LIB = \
                src/drt_fem_general/drt_utils_nurbs_shapefunctions.o \
                src/drt_fem_general/drt_utils_bspline.o \
                src/drt_nurbs_discret/drt_nurbs_discret.o \
                src/drt_nurbs_discret/drt_control_point.o \
                src/drt_nurbs_discret/drt_knotvector.o
OBJS_DRT_NURBS_DISCRET = \
                src/drt_nurbs_discret/drt_apply_nurbs_initial_condition.o
OBJS_DRT      = \
                src/drt_lib/drt_init_control.o \
                src/drt_lib/global_inp_control2.o \
                src/drt_lib/linalg_ana.o \
                src/drt_lib/linalg_condest.o \
                src/drt_lib/linalg_solver.o \
                src/drt_lib/linalg_solver_spooles.o \
                src/drt_lib/linalg_precond.o \
                src/drt_lib/linalg_projected_precond.o \
                src/drt_lib/linalg_projected_operator.o \
                src/drt_lib/linalg_krylov_projector.o \
                src/drt_lib/linalg_mlapi_operator.o \
                src/drt_lib/simpler_operator.o \
                src/drt_lib/saddlepointpreconditioner.o \
                src/drt_lib/transfer_operator.o \
                src/drt_lib/transfer_operator_tentative.o \
                src/drt_lib/transfer_operator_saamg.o \
                src/drt_lib/transfer_operator_pgamg.o \
                src/drt_lib/braesssarazin_smoother.o \
                src/drt_lib/linalg_downwindmatrix.o
#-------------------------------------------------------structural drivers
OBJS_DRT_STRUCTURE      = \
                src/drt_structure/stru_dyn_nln_drt.o \
                src/drt_structure/strugenalpha.o \
                src/drt_structure/strugenalpha_lsnewton.o \
                src/drt_structure/str_aux.o \
                src/drt_structure/strtimint.o \
                src/drt_structure/strtimint_impl.o \
                src/drt_structure/strtimint_impl_nox.o \
                src/drt_structure/strtimint_noxgroup.o \
                src/drt_structure/strtimint_noxlinsys.o \
                src/drt_structure/strtimint_expl.o \
                src/drt_structure/strtimint_statics.o \
                src/drt_structure/strtimint_genalpha.o \
                src/drt_structure/strtimint_ost.o \
                src/drt_structure/strtimint_gemm.o \
                src/drt_structure/strtimint_ab2.o \
                src/drt_structure/strtimint_create.o \
                src/drt_structure/strtimada.o \
                src/drt_structure/strtimada_zienxie.o \
                src/drt_structure/strtimada_create.o \
                src/drt_structure/strudyn_direct.o \
                src/drt_structure/stru_static_drt.o \
                src/drt_structure/stru_resulttest.o \
                src/drt_structure/str_invanalysis.o \
                src/drt_structure/structure_utils_mapextractor.o
#-------------------------------------------------------constraint drivers
OBJS_DRT_CONSTRAINT      = \
                src/drt_constraint/constraint_manager.o \
                src/drt_constraint/constraint.o \
                src/drt_constraint/monitor.o \
                src/drt_constraint/multipointconstraint.o \
                src/drt_constraint/multipointconstraint2.o \
                src/drt_constraint/multipointconstraint3.o \
                src/drt_constraint/mpcdofset.o \
                src/drt_constraint/constraintdofset.o \
                src/drt_constraint/constraintsolver.o
#-------------------------------------------------------constraint elements
OBJS_DRT_CONSTRAINT_LIB      = \
                src/drt_constraint/constraint_element3.o \
                src/drt_constraint/constraint_element3_evaluate.o \
                src/drt_constraint/constraint_element2.o \
                src/drt_constraint/constraint_element2_evaluate.o          
#----------------------------------------------------- drt version mortar
OBJS_DRT_MORTAR_LIB = \
                src/drt_mortar/mortar_element.o \
                src/drt_mortar/mortar_element_integrator.o \
                src/drt_mortar/mortar_element_shapefct.o \
                src/drt_mortar/mortar_node.o
OBJS_DRT_MORTAR = \
                src/drt_mortar/mortar_binarytree.o \
                src/drt_mortar/mortar_coupling2d.o \
                src/drt_mortar/mortar_coupling3d.o \
                src/drt_mortar/mortar_coupling3d_classes.o \
                src/drt_mortar/mortar_defines.o \
                src/drt_mortar/mortar_dofset.o \
                src/drt_mortar/mortar_integrator.o \
                src/drt_mortar/mortar_interface.o \
                src/drt_mortar/mortar_manager_base.o \
                src/drt_mortar/mortar_projector.o \
                src/drt_mortar/mortar_strategy_base.o
#------------------------------------------------ drt version beam contact
OBJS_DRT_BEAMCONTACT_LIB = \
                src/drt_beamcontact/beam3contact.o \
                src/drt_beamcontact/beam3contact_manager.o
OBJS_DRT_BEAMCONTACT = \
                src/drt_beamcontact/beam3contactstrugenalpha.o
#------------------------------------------drt version contact + meshtying
OBJS_DRT_CONTACT_LIB = \
                src/drt_contact/contact_element.o \
                src/drt_contact/contact_node.o \
                src/drt_contact/friction_node.o
OBJS_DRT_CONTACT = \
                src/drt_contact/contact_abstract_strategy.o \
                src/drt_contact/contact_coupling2d.o \
                src/drt_contact/contact_coupling3d.o \
                src/drt_contact/contact_integrator.o \
                src/drt_contact/contact_interface.o \
                src/drt_contact/contact_interface_tools.o \
                src/drt_contact/contact_lagrange_strategy.o \
                src/drt_contact/contact_manager.o \
                src/drt_contact/contact_penalty_strategy.o \
                src/drt_contact/meshtying_abstract_strategy.o \
                src/drt_contact/meshtying_lagrange_strategy.o \
                src/drt_contact/meshtying_manager.o \
                src/drt_contact/meshtying_penalty_strategy.o \
                src/drt_contact/selfcontact_binarytree.o \
                src/drt_contact/strugenalpha_cmt.o
#----------------------------------------------------- drt version statmech
OBJS_DRT_STATMECH = \
                src/drt_statmech/statmech_time.o \
                src/drt_statmech/statmech_manager.o
#----------------------------------------------------- drt version statmech
OBJS_DRT_STATMECH_LIB = src/drt_statmech/bromotion_manager.o
#----------------------------------------------------------thermal drivers
OBJS_DRT_THERMO = \
                src/drt_thermo/thr_dyn.o \
                src/drt_thermo/thr_aux.o \
                src/drt_thermo/thr_resulttest.o \
                src/drt_thermo/thrtimint.o \
                src/drt_thermo/thrtimint_impl.o \
                src/drt_thermo/thrtimint_statics.o \
                src/drt_thermo/thrtimint_ost.o \
                src/drt_thermo/thrtimint_genalpha.o
OBJS_DRT_THERMO_LIB = \
                src/drt_thermo/thermo_element.o \
                src/drt_thermo/thermo_element_input.o \
                src/drt_thermo/thermo_element_evaluate.o \
                src/drt_thermo/thermo_element_boundary_evaluate.o \
                src/drt_thermo/thermo_ele_impl.o \
                src/drt_thermo/thermo_ele_impl_utils.o \
                src/drt_thermo/thermo_ele_boundary_impl.o
# ----------------------------- drt version of thermo structure interaction
OBJS_DRT_TSI  = src/drt_tsi/tsi_algorithm.o \
                src/drt_tsi/tsi_dyn.o \
                src/drt_tsi/tsi_utils.o
# --------------------------------------------------- drt version of fluid
OBJS_DRT_FLUID= src/drt_fluid/fluid_utils.o \
                src/drt_fluid/fluid_utils_mapextractor.o \
                src/drt_fluid/fluid_dyn_nln_drt.o \
                src/drt_fluid/time_integration_scheme.o \
                src/drt_fluid/fluidimplicitintegration.o \
                src/drt_fluid/xfluidimplicitintegration.o \
                src/drt_fluid/fluid_genalpha_integration.o \
                src/drt_fluid/fluid_projectionmethod.o \
                src/drt_fluid/dyn_smag.o \
                src/drt_fluid/fluidimpedancecondition.o \
                src/drt_fluid/drt_transfer_turb_inflow.o \
                src/drt_fluid/turbulence_statistic_manager.o \
                src/drt_fluid/turbulence_statistics_cha.o \
                src/drt_fluid/turbulence_statistics_ccy.o \
                src/drt_fluid/turbulence_statistics_ldc.o \
                src/drt_fluid/turbulence_statistics_bfs.o \
                src/drt_fluid/turbulence_statistics_sqc.o \
                src/drt_fluid/turbulence_statistics_mean_general.o \
                src/drt_fluid/fluidresulttest.o \
                src/drt_fluid/xfluidresulttest.o \
                src/drt_fluid/fluid_coupling_red_models.o \
                src/drt_fluid/fluid_windkessel_optimization.o
# ---------------------------------------------- scalar transport problems
OBJS_DRT_SCATRA = \
                src/drt_scatra/scatra_dyn.o \
                src/drt_scatra/scatra_timint_implicit.o \
                src/drt_scatra/scatra_timint_implicit_service.o \
                src/drt_scatra/scatra_timint_ost.o \
                src/drt_scatra/scatra_timint_bdf2.o \
                src/drt_scatra/scatra_timint_genalpha.o \
                src/drt_scatra/scatra_timint_stat.o \
                src/drt_scatra/scatra_resulttest.o \
                src/drt_scatra/scatra_utils.o \
                src/drt_scatra/passive_scatra_algorithm.o
OBJS_DRT_SCATRA_LIB = \
                src/drt_scatra/scatra_ele_impl.o \
                src/drt_scatra/scatra_ele_impl_utils.o \
                src/drt_scatra/scatra_ele_boundary_impl.o \
                src/drt_scatra/scatra_element.o \
                src/drt_scatra/scatra_element_evaluate.o \
                src/drt_scatra/scatra_element_input.o \
                src/drt_scatra/scatra_element_boundary_evaluate.o
# ----------------------------- drt version of fluid structure interaction
OBJS_DRT_FSI  = src/drt_fsi/fsi_dyn.o \
                src/drt_fsi/fsi_algorithm.o \
                src/drt_fsi/fsi_partitioned.o \
                src/drt_fsi/fsi_dirichletneumann.o \
                src/drt_fsi/fsi_dirichletneumannslideale.o \
                src/drt_fsi/fsi_robinneumann.o \
                src/drt_fsi/fsi_robin.o \
                src/drt_fsi/fsi_structureale.o \
                src/drt_fsi/fsi_monolithic.o \
                src/drt_fsi/fsi_monolithicoverlap.o \
                src/drt_fsi/fsi_monolithiclagrange.o \
                src/drt_fsi/fsi_monolithicstructuresplit.o \
                src/drt_fsi/fsi_monolithicxfem.o \
                src/drt_fsi/fs_monolithic.o \
                src/drt_fsi/fsi_monolithic_linearsystem.o \
                src/drt_fsi/fsi_lungmonolithic.o \
                src/drt_fsi/fsi_lungmonolithic_structuresplit.o \
                src/drt_fsi/fsi_lungmonolithic_fluidsplit.o \
                src/drt_fsi/fsi_constrmonolithic.o \
                src/drt_fsi/fsi_constrmonolithic_fluidsplit.o \
                src/drt_fsi/fsi_constrmonolithic_structuresplit.o \
                src/drt_fsi/fsi_partitionedmonolithic.o \
                src/drt_fsi/fsi_fluid_ale.o \
                src/drt_fsi/fsi_fluid_xfem.o \
                src/drt_fsi/fsi_nox_newton.o \
                src/drt_fsi/fsi_nox_fixpoint.o \
                src/drt_fsi/fsi_nox_aitken.o \
                src/drt_fsi/fsi_nox_jacobian.o \
                src/drt_fsi/fsi_nox_sd.o \
                src/drt_fsi/fsi_nox_linearsystem_gcr.o \
                src/drt_fsi/fsi_nox_linearsystem_bgs.o \
                src/drt_fsi/fsi_nox_linearsystem_partitioned.o \
                src/drt_fsi/fsi_nox_mpe.o \
                src/drt_fsi/fsi_nox_epsilon.o \
                src/drt_fsi/fsi_nox_group.o \
                src/drt_fsi/fsi_utils.o \
                src/drt_fsi/fsi_matrixtransform.o \
                src/drt_fsi/fsi_debugwriter.o \
                src/drt_fsi/fsi_statustest.o \
                src/drt_fsi/fsi_lagrangeprec.o \
                src/drt_fsi/fsi_overlapprec.o \
                src/drt_fsi/fsi_overlapprec_fsiamg.o
OBJS_DRT_ALEALG= src/drt_ale/ale_dyn.o \
                src/drt_ale/ale.o \
                src/drt_ale/ale_lin.o \
                src/drt_ale/ale_laplace.o \
                src/drt_ale/ale_springs.o \
                src/drt_ale/ale_springs_fixed_ref.o \
                src/drt_ale/ale_utils_mapextractor.o \
                src/drt_ale/ale_resulttest.o
OBJS_DRT_ADAPT= src/drt_adapter/adapter_algorithmbase.o \
                src/drt_adapter/adapter_fluid.o \
                src/drt_adapter/adapter_structure.o \
                src/drt_adapter/adapter_structure_strugenalpha.o \
                src/drt_adapter/adapter_structure_timint.o \
                src/drt_adapter/adapter_structure_timint_expl.o \
                src/drt_adapter/adapter_structure_timint_adaptive.o \
                src/drt_adapter/adapter_structure_constr_merged.o \
                src/drt_adapter/adapter_structure_lung.o \
                src/drt_adapter/adapter_structure_wrapper.o \
                src/drt_adapter/adapter_thermo.o \
                src/drt_adapter/adapter_thermo_timint.o \
                src/drt_adapter/adapter_fluid_base_algorithm.o \
                src/drt_adapter/adapter_fluid_ale.o \
                src/drt_adapter/adapter_fluid_xfem.o \
                src/drt_adapter/adapter_fluid_moving_boundary.o \
                src/drt_adapter/adapter_fluid_impl.o \
                src/drt_adapter/adapter_fluid_genalpha.o \
                src/drt_adapter/adapter_xfluid_impl.o \
                src/drt_adapter/adapter_fluid_lung.o \
                src/drt_adapter/adapter_scatra_base_algorithm.o \
                src/drt_adapter/adapter_scatra_fluid_coupling_algorithm.o \
                src/drt_adapter/adapter_scatra_fluid_ale_coupling_algo.o \
                src/drt_adapter/adapter_coupling.o \
                src/drt_adapter/adapter_coupling_mortar.o \
                src/drt_adapter/adapter_fluid_combust.o \
                src/drt_adapter/adapter_fluid_projection.o
#                pss_full
OBJS_PSS      = src/pss_full/pss_am.o \
                src/pss_full/pss_table.o \
                src/pss_full/pss_table_iter.o
#                input_full
OBJS_INPUT    = 
# c++ part of input
OBJS_INPUT_CPP= src/input_full/input_parameterlist.o
# -------------------------------------------------- drt version of fluid3
OBJS_DRT_F3_LIB = src/drt_f3/fluid3.o \
                  src/drt_f3/fluid3_nurbs.o \
                  src/drt_f3/fluid3_impl.o \
                  src/drt_f3/fluid3_lin_impl.o \
                  src/drt_f3/fluid3_genalpha_resVMM.o \
                  src/drt_f3/fluid3_stationary.o \
                  src/drt_f3/fluid3_element_boundary_evaluate.o \
                  src/drt_f3/fluid3_element_boundary.o \
                  src/drt_f3/fluid3_boundary_impl.o \
                  src/drt_f3/fluid3_input.o \
                  src/drt_f3/fluid3_evaluate.o \
                  src/drt_f3/fluid3_weak_dbc.o \
                  src/drt_f3/fluid3_stabilization.o \
                  src/drt_f3/xfluid3.o \
                  src/drt_f3/xfluid3_line.o \
                  src/drt_f3/xfluid3_surface.o \
                  src/drt_f3/xfluid3_input.o \
                  src/drt_f3/xfluid3_evaluate.o \
                  src/drt_f3/xfluid3_surface_evaluate.o \
                  src/drt_f3/xfluid3_line_evaluate.o \
                  src/drt_f3/xfluid3_sysmat_sigma.o \
                  src/drt_f3/xfluid3_sysmat_tau_pressure.o \
                  src/drt_f3/xfluid3_sysmat_projection.o \
                  src/drt_xdiff3/xdiff3.o \
                  src/drt_xdiff3/xdiff3_line.o \
                  src/drt_xdiff3/xdiff3_surface.o \
                  src/drt_xdiff3/xdiff3_input.o \
                  src/drt_xdiff3/xdiff3_evaluate.o \
                  src/drt_xdiff3/xdiff3_surface_evaluate.o \
                  src/drt_xdiff3/xdiff3_line_evaluate.o \
                  src/drt_xdiff3/xdiff3_sysmat4.o \
                  src/drt_fluid/time_integration_element.o
OBJS_DRT_F3   =
#------------------------------------------------------------------ fluid3
OBJS_FLUID3   = 
#               fluid3_fast
OBJS_F3F      = 
#               fluid3_fast (fortran)
OBJS_F3F_F    = 
# -------------------------------------------------- drt version of shell8
OBJS_DRT_S8_LIB = src/drt_s8/shell8.o \
                  src/drt_s8/shell8_line.o
OBJS_DRT_S8   = src/drt_s8/shell8_evaluate.o \
                src/drt_s8/shell8_input.o \
                src/drt_s8/shell8_line_evaluate.o
# -------------------------------------------------- drt version of beam2
OBJS_DRT_B2_LIB   = src/drt_beam2/beam2.o \
                src/drt_beam2/beam2_input.o \
                src/drt_beam2/beam2_evaluate.o
OBJS_DRT_B2   =
# -------------------------------------------------- drt version of beam2r
OBJS_DRT_B2R_LIB   = src/drt_beam2r/beam2r.o \
                src/drt_beam2r/beam2r_input.o \
                src/drt_beam2r/beam2r_evaluate.o
OBJS_DRT_B2R   =
# -------------------------------------------------- drt version of beam3
OBJS_DRT_B3_LIB   = src/drt_beam3/beam3.o \
                src/drt_beam3/beam3_input.o \
                src/drt_beam3/beam3_evaluate.o
OBJS_DRT_B3   =
# -------------------------------------------------- drt version of truss3
OBJS_DRT_T3_LIB   = src/drt_truss3/truss3.o \
                src/drt_truss3/truss3_input.o \
                src/drt_truss3/truss3_evaluate.o
OBJS_DRT_T3   =
# -------------------------------------------------- drt version of smoothrod
OBJS_DRT_SR_LIB   = src/drt_smoothrod/smoothrod.o \
                src/drt_smoothrod/smoothrod_input.o \
                src/drt_smoothrod/smoothrod_evaluate.o
OBJS_DRT_SR   =
# -------------------------------------------------- drt version of truss2
OBJS_DRT_T2_LIB   = src/drt_truss2/truss2.o \
                src/drt_truss2/truss2_input.o \
                src/drt_truss2/truss2_evaluate.o
OBJS_DRT_T2   =
# -------------------------------------------------- drt version of torsion3
OBJS_DRT_TO3_LIB   = src/drt_torsion3/torsion3.o \
                src/drt_torsion3/torsion3_input.o \
                src/drt_torsion3/torsion3_evaluate.o
OBJS_DRT_TO3   =
# -------------------------------------------------- drt version of torsion2
OBJS_DRT_TO2_LIB   = src/drt_torsion2/torsion2.o \
                src/drt_torsion2/torsion2_input.o \
                src/drt_torsion2/torsion2_evaluate.o
OBJS_DRT_TO2   =
#-------------------------------------------------- old version of shell8
OBJS_SHELL8   = src/shell8/s8_mat_ogden.o \
                src/shell8/s8_mat_ogden2.o \
                src/shell8/s8_mat_ogden3.o \
                src/shell8/s8_tmat.o \
                src/shell8/s8_mattransform.o \
                src/shell8/s8_mat_linel.o
#               ale
OBJS_ALE      = 
OBJS_DRT_ALE_LIB = src/drt_ale3/ale3.o \
                src/drt_ale3/ale3_nurbs.o \
                src/drt_ale3/ale3_surface.o \
                src/drt_ale2/ale2.o \
                src/drt_ale2/ale2_line.o \
                src/drt_ale2/ale2_nurbs.o \
                src/drt_ale3/ale3_evaluate.o \
                src/drt_ale3/ale3_input.o \
                src/drt_ale3/ale3_surface_evaluate.o \
                src/drt_ale2/ale2_evaluate.o \
                src/drt_ale2/ale2_input.o \
                src/drt_ale2/ale2_line_evaluate.o
OBJS_DRT_ALE   =
#               parallel
OBJS_PAR      = 
#------------------------------------------------ drt solids
OBJS_SOH8     =
OBJS_SOH8_LIB = src/drt_so3/so_hex8.o \
                src/drt_so3/so_sh8.o \
                src/drt_so3/so_hex8_evaluate.o \
                src/drt_so3/so_hex8_thermo_evaluate.o \
                src/drt_so3/so_material.o \
                src/drt_so3/so_hex8_eas.o \
                src/drt_so3/so_hex8_input.o \
                src/drt_so3/so_hex8_service.o \
                src/drt_so3/so_hex8_multiscale.o \
                src/drt_so3/so_sh8_input.o \
                src/drt_so3/so_sh8_evaluate.o \
                src/drt_so3/so_sh8_service.o \
                src/drt_so3/so_sh8p8.o \
                src/drt_so3/so_sh8p8_input.o \
                src/drt_so3/so_sh8p8_evaluate.o \
                src/drt_so3/so_sh8p8_auxiliar.o \
                src/drt_so3/so_sh8p8_eas.o \
                src/drt_so3/so_tet4.o \
                src/drt_so3/so_tet4_evaluate.o \
                src/drt_so3/so_tet4_input.o \
                src/drt_so3/so_nstet.o \
                src/drt_so3/so_nstet_evaluate.o \
                src/drt_so3/so_nstet_nodalstrain.o \
                src/drt_so3/so_nstet_input.o \
                src/drt_so3/so_ptet.o \
                src/drt_so3/so_ptet_evaluate.o \
                src/drt_so3/so_ptet_nodalstrain.o \
                src/drt_so3/so_ptet_input.o \
                src/drt_so3/inversedesign.o \
                src/drt_so3/inversedesign_evaluate.o \
                src/drt_so3/prestress.o \
                src/drt_so3/so_tet10.o \
                src/drt_so3/so_tet10_evaluate.o \
                src/drt_so3/so_tet10_input.o \
                src/drt_so3/so_weg6.o \
                src/drt_so3/so_weg6_evaluate.o \
                src/drt_so3/so_weg6_input.o \
                src/drt_so3/so_disp.o \
                src/drt_so3/so_disp_input.o \
                src/drt_so3/so_disp_evaluate.o \
                src/drt_so3/so_shw6.o \
                src/drt_so3/so_shw6_evaluate.o \
                src/drt_so3/so_shw6_input.o \
                src/drt_so3/so_surface.o \
                src/drt_so3/so_surface_evaluate.o \
                src/drt_so3/so_line.o \
                src/drt_so3/so_line_evaluate.o \
                src/drt_so3/so_hex27.o \
                src/drt_so3/so_hex27_evaluate.o \
                src/drt_so3/so_hex27_input.o \
                src/drt_so3/so_hex27_service.o \
                src/drt_so3/so_hex27_multiscale.o \
                src/drt_so3/so_nurbs27.o \
                src/drt_so3/so_nurbs27_input.o \
                src/drt_so3/so_nurbs27_evaluate.o \
                src/drt_so3/so_hex20.o \
                src/drt_so3/so_hex20_evaluate.o \
                src/drt_so3/so_hex20_input.o \
                src/drt_so3/so_hex20_service.o \
                src/drt_so3/so_hex20_multiscale.o \
                src/drt_so3/so_hex8p1j1.o \
                src/drt_so3/so_hex8p1j1_input.o \
                src/drt_so3/so_hex8p1j1_evaluate.o
#--------------------------------------------------------- brick1
OBJS_BRICK1   = 
#               math
OBJS_MATH     = src/math/math1.o
#               output
OBJS_OUTPUT   = 
#                io
OBJS_IO       = 
#
OBJS_DRT_IO_LIB = src/drt_io/io.o \
                src/drt_io/io_hdf.o \
                src/drt_io/io_control.o \
                src/drt_io/io_gmsh.o \
                src/drt_io/io_gmsh_xfem_extension.o
#------------------------------------------------- w1 drt version
OBJS_DRT_W1_LIB = src/drt_w1/wall1.o \
                src/drt_w1/wall1_nurbs.o \
                src/drt_w1/wall1_line.o \
                src/drt_w1/wall1_evaluate.o \
                src/drt_w1/wall1_mat.o \
                src/drt_w1/wall1_eas.o \
                src/drt_w1/wall1_gemm.o \
                src/drt_w1/wall1_input.o \
                src/drt_w1/wall1_line_evaluate.o
OBJS_DRT_W1   =
#---------------------------------------------------------- wall1
OBJS_WALL1    = 
#------------------------------------ fluid2 (drt version)
OBJS_DRT_F2_LIB = src/drt_f2/fluid2_evaluate.o \
                src/drt_f2/fluid2_input.o \
                src/drt_f2/fluid2_line_evaluate.o \
                src/drt_f2/fluid2_weak_dbc.o \
                src/drt_f2/fluid2.o \
                src/drt_f2/fluid2_nurbs.o \
                src/drt_f2/fluid2_line.o \
                src/drt_f2/fluid2_impl.o \
                src/drt_f2/fluid2_stationary.o \
                src/drt_f2/fluid2_genalpha_resVMM.o \
                src/drt_f2/fluid2_th.o
OBJS_DRT_F2 =
#------------------------------------------------- fluid2
OBJS_FLUID2   = 
#               fluid2_TDS
OBJS_F2_TDS   = 
#               fluid_full
OBJS_FLUID    = 
#               fsi_full
OBJS_FSI      = 
#
OBJS_FSI_CPP  = 
#                shell9
OBJS_SHELL9   = 
#               beam3
OBJS_BEAM3    = 
#               fluid2 multilevel
OBJS_F2ML     = 
#               fluid3 multilevel
OBJS_F3ML     = 
#                stucture 2D ml
OBJS_S2ML     = 
#                optimization
OBJS_OPT      = 
#                axishell
OBJS_AXISHELL = 
#               materials
OBJS_MAT      = 
#               materials for new discretization
OBJS_DRT_MAT_LIB = src/drt_mat/matpar_bundle.o \
                src/drt_mat/matpar_material.o \
                src/drt_mat/matpar_parameter.o \
                src/drt_mat/micromaterial.o \
                src/drt_mat/newtonianfluid.o \
                src/drt_mat/stvenantkirchhoff.o \
                src/drt_mat/thermostvenantkirchhoff.o \
                src/drt_mat/lung_penalty.o \
                src/drt_mat/lung_ogden.o \
                src/drt_mat/neohooke.o \
                src/drt_mat/plasticneohooke.o \
                src/drt_mat/visconeohooke.o \
                src/drt_mat/viscoanisotropic.o \
                src/drt_mat/aaaneohooke.o \
                src/drt_mat/aaagasser.o \
                src/drt_patspec/patspec.o \
                src/drt_mat/aaaraghavanvorp_damage.o \
                src/drt_mat/logneohooke.o \
                src/drt_mat/anisotropic_balzani.o \
                src/drt_mat/mooneyrivlin.o \
                src/drt_mat/yeoh.o \
                src/drt_mat/contchainnetw.o \
                src/drt_mat/artwallremod.o \
                src/drt_mat/biocell.o \
                src/drt_mat/scatra_mat.o \
                src/drt_mat/mixfrac.o \
                src/drt_mat/sutherland.o \
                src/drt_mat/arrhenius_spec.o \
                src/drt_mat/arrhenius_temp.o \
                src/drt_mat/arrhenius_pv.o \
                src/drt_mat/ferech_pv.o \
                src/drt_mat/carreauyasuda.o \
                src/drt_mat/modpowerlaw.o \
                src/drt_mat/material.o \
                src/drt_mat/matlist.o \
                src/drt_mat/ion.o \
                src/drt_mat/compogden.o \
                src/drt_mat/charmm.o \
                src/drt_mat/protein.o \
                src/drt_mat/itskov.o \
                src/drt_mat/elasthyper.o \
                src/drt_matelast/elast_summand.o \
                src/drt_matelast/elast_couplogneohooke.o \
                src/drt_matelast/elast_coupblatzko.o \
                src/drt_matelast/elast_isoneohooke.o \
                src/drt_matelast/elast_isoexpo.o \
                src/drt_matelast/elast_isomooneyrivlin.o \
                src/drt_matelast/elast_isoyeoh.o \
                src/drt_matelast/elast_isoquad.o \
                src/drt_matelast/elast_isocub.o \
                src/drt_matelast/elast_coupanisoexpotwo.o \
                src/drt_matelast/elast_coupanisoneohooketwo.o \
                src/drt_matelast/elast_volsussmanbathe.o \
                src/drt_matelast/elast_volpenalty.o \
                src/drt_matelast/elast_vologden.o \
                src/drt_matelast/elast_coupvarga.o \
                src/drt_matelast/elast_isovarga.o \
                src/drt_mat/cnst_1d_art.o \
                src/drt_mat/fourieriso.o \
                src/drt_mat/holzapfelcardiovascular.o \
                src/drt_mat/humphreycardiovascular.o
#
OBJS_DRT_MAT  = src/drt_mat/micromaterialgp_static.o \
                src/drt_mat/micromaterial_evaluate.o
#               structural multiscale in new discretization
OBJS_DRT_STRU_MULTI = src/drt_stru_multi/microstatic.o \
                      src/drt_stru_multi/convert_mat.o
#               surface stresses due to interfacial phenomena
OBJS_DRT_SURFSTRESS = src/drt_surfstress/drt_surfstress_manager.o 
          
#               intermolecular interaction phenomena                   
OBJS_DRT_POTENTIAL =  src/drt_potential/drt_potential_container.o \
                      src/drt_potential/drt_potential_dofset.o \
                      src/drt_potential/drt_potential.o \
                      src/drt_potential/drt_potential_surface.o \
                      src/drt_potential/drt_potential_volume.o \
                      src/drt_potential/drt_potential_manager.o
                      
#               structure-structure interaction
OBJS_SSI      = 
#
OBJS_F2PRO    = 
#
OBJS_F3PRO    = 
#
OBJS_F2IS     = 
#
OBJS_F3IS     = 
#               interf
OBJS_IF       = 
#               gradient enhanced wall
OBJS_WALLGE   = 
#               thermal structure interaction
OBJS_TSI      = 
#               planar thermal
OBJS_THERM2   = 
#               spatial thermal
OBJS_THERM3   = 
#               spatial structural
OBJS_SOLID3   = 
#               visual
OBJS_VISUAL   = 
#               fortran parallel and sequentiell on HPUX10.20 / Linux / Sun
OBJS_FORTRAN  = src/fortran/s8_fserv.o \
                src/fortran/hex_fserv.o
#               fortran parallel on HPUX11.0
#               C PLUS PLUS
OBJS_NURBS_CPP  = 

#                post_common
OBJS_POST_COMMON = src/post_common/post_am.o \
                src/post_common/post_ds.o \
                src/post_common/post_perf.o \
                src/post_common/post_table.o \
                src/post_common/post_table_iter.o \
                src/post_common/post_elements.o \
                src/post_common/post_set.o \
                src/post_common/post_design.o \
                src/post_common/post_octtree.o \
                src/post_common/post_common.o

OBJS_POST_DRT_COMMON = src/post_drt_common/post_drt_common.o

#                post_gid
OBJS_POST_GID_COMMON = src/post_gid/post_gid.o \
                src/post_gid/shell9_intg.o \
                src/post_gid/shell9_funcderiv.o \
                src/post_gid/post_ale2.o \
                src/post_gid/post_ale3.o \
                src/post_gid/post_axishell.o \
                src/post_gid/post_beam3.o \
                src/post_gid/post_brick1.o \
                src/post_gid/post_fluid2.o \
                src/post_gid/post_fluid2_pro.o \
                src/post_gid/post_fluid2_is.o \
                src/post_gid/post_fluid3.o \
                src/post_gid/post_fluid3_fast.o \
                src/post_gid/post_fluid3_pro.o \
                src/post_gid/post_fluid3_is.o \
                src/post_gid/post_interf.o \
                src/post_gid/post_shell8.o \
                src/post_gid/post_shell9.o \
                src/post_gid/post_wall1.o \
                src/post_gid/post_wallge.o \
                src/post_gid/post_solid3.o

OBJS_POST_GID_BIN = src/post_gid/gid_out.o \
                src/post_gid/zlibint1.o \
                src/post_gid/zlibint2.o

OBJS_POST_GID_TXT = src/post_gid/gid_out_txt.o

OBJS_POST_DRT_GID = src/post_gid/post_drt_gid.o

OBJS_POST_DRT_ENSIGHT = src/post_ensight/post_drt_ensight_writer.o \
                src/post_ensight/post_drt_ensight_writer_nurbs.o \
                src/post_ensight/post_drt_ensight_single_field_writers.o \
                src/post_ensight/post_drt_ensight_structure_stress.o \
                src/post_ensight/post_drt_ensight_thermo_heatflux.o \
                src/post_ensight/post_drt_ensight.o

OBJS_POST_DRT_MONITOR = src/post_monitor/post_drt_monitor.o

OBJS_POST_DRT_S8CONVERT = src/post_s8convert/post_drt_s8convert.o

OBJS_POST_DRT_Q9NECONVERT = src/post_q9neconvert/post_drt_q9neconvert.o

#                 object to mimik baci-objects for pre and post filters
OBJS_FILTER_COMMON = src/filter_common/filter_evaluation.o

#                 pre_exodus
OBJS_PRE_EXODUS = src/pre_exodus/pre_exodus.o \
                  src/pre_exodus/pre_exodus_reader.o \
                  src/pre_exodus/pre_exodus_soshextrusion.o \
                  src/pre_exodus/pre_exodus_centerline.o \
                  src/pre_exodus/pre_exodus_writedat.o \
                  src/pre_exodus/pre_exodus_readbc.o \
                  src/pre_exodus/pre_exodus_validate.o

#                 pre_curve
OBJS_PRE_CURVE = src/pre_curve/pre_curve.o

#                 post_out
OBJS_POST_OUT = src/post_out/post_out.o

#                 post_visual2
OBJS_POST_VISUAL2 = src/post_visual/post_visual2.o

#                 post_visual3
OBJS_POST_VISUAL3 = src/post_visual/post_visual3.o \
                src/post_visual/post_visual3_functions.o

#                 post_monitor
OBJS_POST_MONITOR = src/post_monitor/post_monitor.o \
                src/post_monitor/post_out_monitor.o
#               post_file_manager
OBJS_POST_FILE_MANAGER = src/post_file_manager/post_file_manager.o
                #src/post_visual/post_map_functions.o
#               ensight_file_converter
OBJS_POST_ENSIGHT = src/post_ensight/post_ensight.o \
                src/post_ensight/post_functions.o
#               post_cmp
OBJS_POST_CMP = src/post_cmp/post_cmp.o

#               test_intersection
OBJS_INTERSECTION = src/drt_xfem/physics.o \
                    src/drt_xfem/field_enriched.o \
                    src/drt_xfem/dof_management.o \
                    src/drt_xfem/dof_management_element.o \
                    src/drt_xfem/dof_distribution_switcher.o \
                    src/drt_xfem/enrichment.o \
                    src/drt_xfem/interface.o \
                    src/drt_xfem/interfacexfsi.o \
                    src/drt_xfem/spacetime_boundary.o \
                    src/drt_xfem/enrichment_utils.o \
                    src/drt_xfem/xdofmapcreation.o \
                    src/drt_xfem/xdofmapcreation_combust.o \
                    src/drt_xfem/xdofmapcreation_parallel_utils.o \
                    src/drt_xfem/xdofmapcreation_fsi.o
#               inverse analysis
OBJS_INV_ANALYSIS = src/drt_inv_analysis/inv_analysis.o \
                    src/drt_inv_analysis/airways_inv_analysis.o\
                    src/drt_inv_analysis/gen_inv_analysis.o
#               low-Mach-number flow
OBJS_DRT_LOMA = src/drt_loma/loma_dyn.o \
                src/drt_loma/loma_algorithm.o
#               electrochemistry
OBJS_DRT_ELCH = src/drt_elch/elch_dyn.o \
                src/drt_elch/elch_algorithm.o \
                src/drt_elch/elch_moving_boundary_algorithm.o
#------------------------------------------------ combustion (drt version)
OBJS_DRT_COMBUST =  src/drt_combust/combust_dyn.o \
                    src/drt_combust/combust_algorithm.o \
                    src/drt_combust/combust_utils.o \
                    src/drt_combust/combust_interface.o \
                    src/drt_combust/combust_refinementcell.o \
                    src/drt_combust/combust_reinitializer.o \
                    src/drt_combust/combust_flamefront.o \
                    src/drt_combust/combust_fluidimplicitintegration.o \
                    src/drt_combust/combust_fluidresulttest.o
#------------------------------------------------ combustion (drt version)
OBJS_DRT_COMBUST3_LIB = src/drt_combust/combust3.o \
                        src/drt_combust/combust3_evaluate.o \
                        src/drt_combust/combust3_input.o \
                        src/drt_combust/combust3_line.o \
                        src/drt_combust/combust3_line_evaluate.o \
                        src/drt_combust/combust3_surface.o \
                        src/drt_combust/combust3_surface_evaluate.o \
                        src/drt_combust/combust3_sysmat.o
#------------------------------------------------ arterial network (drt version)
OBJS_DRT_ARTNET =  src/drt_art_net/art_net_dyn_drt.o \
                   src/drt_art_net/artnetexplicitintegration.o
#------------------------------------------------ arterial network (drt version)
OBJS_DRT_ARTNET_LIB =  src/drt_art_net/artery.o \
                       src/drt_art_net/artery_evaluate.o \
                       src/drt_art_net/artery_input.o \
                       src/drt_art_net/artery_lin_exp.o\
                       src/drt_art_net/art_junction.o\
                       src/drt_art_net/art_write_gnuplot.o\
                       src/drt_art_net/art_terminal_bc.o
#------------------------------------- reduced dimensional airways (drt version)
OBJS_DRT_RED_AIRWAYS =  src/drt_red_airways/red_airways_dyn_drt.o \
                        src/drt_red_airways/airwayimplicitintegration.o 
#------------------------------------- reduced dimensional airways (drt version)
OBJS_DRT_RED_AIRWAYS_LIB =  src/drt_red_airways/red_airway.o \
                            src/drt_red_airways/airway_evaluate.o \
                            src/drt_red_airways/red_airway_input.o \
                            src/drt_red_airways/airway_impl.o
#------------------------------------fsi effects in biosimulations (drt version)
OBJS_DRT_ALE_BFLOW = 
# boundary elements
OBJS_DRT_BELE3_LIB = src/drt_bele3/bele3.o \
                  src/drt_bele3/bele3_line.o \
                  src/drt_bele3/bele3_line_evaluate.o \
                  src/drt_bele3/bele3_evaluate.o \
                  src/drt_bele3/bele2.o \
                  src/drt_bele3/bele2_evaluate.o  \
                  src/drt_bele3/vele3.o \
                  src/drt_bele3/vele3_line.o \
                  src/drt_bele3/vele3_line_evaluate.o \
                  src/drt_bele3/vele3_surface.o \
                  src/drt_bele3/vele3_surface_evaluate.o \
                  src/drt_bele3/vele3_evaluate.o
