#--------------------------------------------------------------------
# enter path to the individual source directory
#--------------------------------------------------------------------
#SRC       = /bau/statik/<name>/wdir/ccarat/
