#--------------------------------------------------------------------
# enter path to the individual source directory
#--------------------------------------------------------------------
SRC       =  /bau/stat31/users/statik/lipka/wdir/cca_okt/ccarat
