# This is the base of all unittests
find_package( CxxTest 4 )
if ( CXXTEST_FOUND )
  enable_testing()
  add_subdirectory ( Unittests )
else ()
  message("WW *************************************************************")
  message("WW Warning: CxxTest not found. Unittests not available in BACI.")
  message("WW Warning: To enable unit tests, install 'cxxtest'.")
  message("WW ************************************************************")
endif ( CXXTEST_FOUND )
