/*----------------------------------------------------------------------*/
/*! \file

\brief Implementation of registration of parallel objects

\level 1


*/
/*----------------------------------------------------------------------*/

#include "baci_global_legacy_module.hpp"

#include "baci_ale_ale2.hpp"
#include "baci_ale_ale2_nurbs.hpp"
#include "baci_ale_ale3.hpp"
#include "baci_ale_ale3_nurbs.hpp"
#include "baci_art_net_artery.hpp"
#include "baci_beam3_euler_bernoulli.hpp"
#include "baci_beam3_kirchhoff.hpp"
#include "baci_beam3_reissner.hpp"
#include "baci_beaminteraction_crosslinker_node.hpp"
#include "baci_beaminteraction_link_beam3_reissner_line2_pinjointed.hpp"
#include "baci_beaminteraction_link_beam3_reissner_line2_rigidjointed.hpp"
#include "baci_beaminteraction_link_truss.hpp"
#include "baci_bele_bele3.hpp"
#include "baci_bele_vele3.hpp"
#include "baci_binstrategy_meshfree_multibin.hpp"
#include "baci_constraint_element2.hpp"
#include "baci_constraint_element3.hpp"
#include "baci_contact_element.hpp"
#include "baci_contact_friction_node.hpp"
#include "baci_contact_node.hpp"
#include "baci_elemag_diff_ele.hpp"
#include "baci_elemag_ele.hpp"
#include "baci_fluid_ele.hpp"
#include "baci_fluid_ele_hdg.hpp"
#include "baci_fluid_ele_hdg_weak_comp.hpp"
#include "baci_fluid_ele_immersed.hpp"
#include "baci_fluid_ele_poro.hpp"
#include "baci_fluid_ele_xwall.hpp"
#include "baci_fluid_functions.hpp"
#include "baci_fluid_xfluid_functions.hpp"
#include "baci_fluid_xfluid_functions_combust.hpp"
#include "baci_lib_immersed_node.hpp"
#include "baci_lubrication_ele.hpp"
#include "baci_mat_aaa_mixedeffects.hpp"
#include "baci_mat_aaagasser.hpp"
#include "baci_mat_aaaneohooke.hpp"
#include "baci_mat_aaaneohooke_stopro.hpp"
#include "baci_mat_aaaraghavanvorp_damage.hpp"
#include "baci_mat_arrhenius_pv.hpp"
#include "baci_mat_arrhenius_spec.hpp"
#include "baci_mat_arrhenius_temp.hpp"
#include "baci_mat_beam_elasthyper.hpp"
#include "baci_mat_carreauyasuda.hpp"
#include "baci_mat_cnst_1d_art.hpp"
#include "baci_mat_constraintmixture.hpp"
#include "baci_mat_constraintmixture_history.hpp"
#include "baci_mat_crystal_plasticity.hpp"
#include "baci_mat_damage.hpp"
#include "baci_mat_elasthyper.hpp"
#include "baci_mat_elchmat.hpp"
#include "baci_mat_electromagnetic.hpp"
#include "baci_mat_ferech_pv.hpp"
#include "baci_mat_fluid_linear_density_viscosity.hpp"
#include "baci_mat_fluid_murnaghantait.hpp"
#include "baci_mat_fluid_weakly_compressible.hpp"
#include "baci_mat_fluidporo.hpp"
#include "baci_mat_fluidporo_multiphase.hpp"
#include "baci_mat_fluidporo_multiphase_reactions.hpp"
#include "baci_mat_fluidporo_multiphase_singlereaction.hpp"
#include "baci_mat_fluidporo_singlephase.hpp"
#include "baci_mat_fourieriso.hpp"
#include "baci_mat_growth.hpp"
#include "baci_mat_growthremodel_elasthyper.hpp"
#include "baci_mat_herschelbulkley.hpp"
#include "baci_mat_ion.hpp"
#include "baci_mat_lin_elast_1D.hpp"
#include "baci_mat_list.hpp"
#include "baci_mat_list_chemoreac.hpp"
#include "baci_mat_list_chemotaxis.hpp"
#include "baci_mat_list_reactions.hpp"
#include "baci_mat_maxwell_0d_acinus.hpp"
#include "baci_mat_maxwell_0d_acinus_DoubleExponential.hpp"
#include "baci_mat_maxwell_0d_acinus_Exponential.hpp"
#include "baci_mat_maxwell_0d_acinus_NeoHookean.hpp"
#include "baci_mat_maxwell_0d_acinus_Ogden.hpp"
#include "baci_mat_membrane_active_strain.hpp"
#include "baci_mat_membrane_elasthyper.hpp"
#include "baci_mat_micromaterial.hpp"
#include "baci_mat_mixfrac.hpp"
#include "baci_mat_mixture.hpp"
#include "baci_mat_modpowerlaw.hpp"
#include "baci_mat_myocard.hpp"
#include "baci_mat_newtonianfluid.hpp"
#include "baci_mat_plastic_VarConstUpdate.hpp"
#include "baci_mat_plasticelasthyper.hpp"
#include "baci_mat_plasticlinelast.hpp"
#include "baci_mat_robinson.hpp"
#include "baci_mat_scalardepinterp.hpp"
#include "baci_mat_scatra.hpp"
#include "baci_mat_scatra_multiporo.hpp"
#include "baci_mat_scatra_poro_ecm.hpp"
#include "baci_mat_spring.hpp"
#include "baci_mat_structporo.hpp"
#include "baci_mat_structporo_reaction.hpp"
#include "baci_mat_structporo_reaction_ecm.hpp"
#include "baci_mat_stvenantkirchhoff.hpp"
#include "baci_mat_sutherland.hpp"
#include "baci_mat_tempdepwater.hpp"
#include "baci_mat_thermoplasticlinelast.hpp"
#include "baci_mat_thermostvenantkirchhoff.hpp"
#include "baci_mat_viscoanisotropic.hpp"
#include "baci_mat_viscoelasthyper.hpp"
#include "baci_mat_visconeohooke.hpp"
#include "baci_mat_yoghurt.hpp"
#include "baci_membrane_eletypes.hpp"
#include "baci_membrane_scatra_eletypes.hpp"
#include "baci_module_registry_callbacks.hpp"
#include "baci_mortar_element.hpp"
#include "baci_mortar_node.hpp"
#include "baci_nurbs_discret_control_point.hpp"
#include "baci_particle_engine_object.hpp"
#include "baci_porofluidmultiphase_ele.hpp"
#include "baci_poromultiphase_scatra_function.hpp"
#include "baci_red_airways_elementbase.hpp"
#include "baci_rigidsphere.hpp"
#include "baci_scatra_ele.hpp"
#include "baci_shell7p_ele.hpp"
#include "baci_shell7p_ele_scatra.hpp"
#include "baci_so3_hex18.hpp"
#include "baci_so3_hex20.hpp"
#include "baci_so3_hex27.hpp"
#include "baci_so3_hex8.hpp"
#include "baci_so3_hex8fbar.hpp"
#include "baci_so3_hex8p1j1.hpp"
#include "baci_so3_nstet5.hpp"
#include "baci_so3_nurbs27.hpp"
#include "baci_so3_plast_ssn_eletypes.hpp"
#include "baci_so3_plast_ssn_sosh18.hpp"
#include "baci_so3_plast_ssn_sosh8.hpp"
#include "baci_so3_poro_eletypes.hpp"
#include "baci_so3_poro_p1_eletypes.hpp"
#include "baci_so3_poro_p1_scatra_eletypes.hpp"
#include "baci_so3_poro_scatra_eletypes.hpp"
#include "baci_so3_pyramid5.hpp"
#include "baci_so3_pyramid5fbar.hpp"
#include "baci_so3_scatra_eletypes.hpp"
#include "baci_so3_sh18.hpp"
#include "baci_so3_sh8.hpp"
#include "baci_so3_sh8p8.hpp"
#include "baci_so3_shw6.hpp"
#include "baci_so3_tet10.hpp"
#include "baci_so3_tet4.hpp"
#include "baci_so3_tet4av.hpp"
#include "baci_so3_thermo_eletypes.hpp"
#include "baci_so3_weg6.hpp"
#include "baci_solid_3D_ele.hpp"
#include "baci_solid_poro_3D_ele.hpp"
#include "baci_solid_scatra_3D_ele.hpp"
#include "baci_stru_multi_microstatic.hpp"
#include "baci_structure_new_functions.hpp"
#include "baci_thermo_element.hpp"
#include "baci_torsion3.hpp"
#include "baci_truss3.hpp"
#include "baci_truss3_scatra.hpp"
#include "baci_utils_function_library.hpp"
#include "baci_w1.hpp"
#include "baci_w1_nurbs.hpp"
#include "baci_w1_poro_eletypes.hpp"
#include "baci_w1_poro_p1_eletypes.hpp"
#include "baci_w1_poro_p1_scatra_eletypes.hpp"
#include "baci_w1_poro_scatra_eletypes.hpp"
#include "baci_w1_scatra.hpp"

#include <iostream>
#include <string>

FOUR_C_NAMESPACE_OPEN

namespace
{
  void RegisterParObjectTypes()
  {
    // Perform a dummy operation for the side-effect of forcing registration.
    std::stringstream s;

    s << DRT::NodeType::Instance().Name() << " " << DRT::NURBS::ControlPointType::Instance().Name()
      << " " << DRT::ImmersedNodeType::Instance().Name() << " "
      << CROSSLINKING::CrosslinkerNodeType::Instance().Name() << " "
      << DRT::MESHFREE::MeshfreeMultiBinType::Instance().Name() << " "
      << DRT::ELEMENTS::Beam3rType::Instance().Name() << " "
      << DRT::ELEMENTS::Beam3ebType::Instance().Name() << " "
      << DRT::ELEMENTS::Beam3kType::Instance().Name() << " "
      << DRT::ELEMENTS::RigidsphereType::Instance().Name() << " "
      << DRT::ELEMENTS::Truss3Type::Instance().Name() << " "
      << DRT::ELEMENTS::Truss3ScatraType::Instance().Name() << " "
      << DRT::ELEMENTS::Torsion3Type::Instance().Name() << " "
      << DRT::ELEMENTS::Shell7pType::Instance().Name() << " "
      << DRT::ELEMENTS::Shell7pScatraType::Instance().Name() << " "
      << DRT::ELEMENTS::Membrane_tri3Type::Instance().Name() << " "
      << DRT::ELEMENTS::Membrane_tri6Type::Instance().Name() << " "
      << DRT::ELEMENTS::Membrane_quad4Type::Instance().Name() << " "
      << DRT::ELEMENTS::Membrane_quad9Type::Instance().Name() << " "
      << DRT::ELEMENTS::MembraneScatra_tri3Type::Instance().Name() << " "
      << DRT::ELEMENTS::MembraneScatra_tri6Type::Instance().Name() << " "
      << DRT::ELEMENTS::MembraneScatra_quad4Type::Instance().Name() << " "
      << DRT::ELEMENTS::MembraneScatra_quad9Type::Instance().Name() << " "
      << DRT::ELEMENTS::Wall1Type::Instance().Name() << " "
      << DRT::ELEMENTS::WallTri3PoroType::Instance().Name() << " "
      << DRT::ELEMENTS::WallTri3PoroP1Type::Instance().Name() << " "
      << DRT::ELEMENTS::WallQuad4PoroType::Instance().Name() << " "
      << DRT::ELEMENTS::WallQuad4PoroP1Type::Instance().Name() << " "
      << DRT::ELEMENTS::WallQuad9PoroType::Instance().Name() << " "
      << DRT::ELEMENTS::WallQuad9PoroP1Type::Instance().Name() << " "
      << DRT::ELEMENTS::WallNurbs4PoroType::Instance().Name() << " "
      << DRT::ELEMENTS::WallNurbs9PoroType::Instance().Name() << " "
      << DRT::ELEMENTS::NURBS::Wall1NurbsType::Instance().Name() << " "
      << DRT::ELEMENTS::Wall1ScatraType::Instance().Name() << " "
      << DRT::ELEMENTS::WallQuad4PoroScatraType::Instance().Name() << " "
      << DRT::ELEMENTS::WallQuad4PoroP1ScatraType::Instance().Name() << " "
      << DRT::ELEMENTS::FluidType::Instance().Name() << " "
      << DRT::ELEMENTS::FluidXWallType::Instance().Name() << " "
      << DRT::ELEMENTS::FluidXWallBoundaryType::Instance().Name() << " "
      << DRT::ELEMENTS::FluidTypeImmersed::Instance().Name() << " "
      << DRT::ELEMENTS::FluidPoroEleType::Instance().Name() << " "
      << DRT::ELEMENTS::FluidHDGType::Instance().Name() << " "
      << DRT::ELEMENTS::FluidHDGWeakCompType::Instance().Name() << " "
      << DRT::ELEMENTS::FluidBoundaryType::Instance().Name() << " "
      << DRT::ELEMENTS::FluidPoroBoundaryType::Instance().Name() << " "
      << DRT::ELEMENTS::Ale3Type::Instance().Name() << " "
      << DRT::ELEMENTS::NURBS::Ale3_NurbsType::Instance().Name() << " "
      << DRT::ELEMENTS::Ale2Type::Instance().Name() << " "
      << DRT::ELEMENTS::NURBS::Ale2_NurbsType::Instance().Name() << " "
      << DRT::ELEMENTS::Bele3Type::Instance().Name() << " "
      << DRT::ELEMENTS::Vele3Type::Instance().Name() << " "
      << DRT::ELEMENTS::NStet5Type::Instance().Name() << " "
      << DRT::ELEMENTS::NURBS::So_nurbs27Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_nurbs27PoroType::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex18Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_sh18Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_sh18PlastType::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex8Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_Hex8P1J1Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex8fbarType::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex8fbarScatraType::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex8fbarThermoType::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex8PoroType::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex8PoroP1Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex8ScatraType::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex8ThermoType::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex8PlastType::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex8Type::Instance().Name() << " "
      << DRT::ELEMENTS::SolidType::Instance().Name() << " "
      << DRT::ELEMENTS::SolidPoroType::Instance().Name() << " "
      << DRT::ELEMENTS::SolidScatraType::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex20Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex27Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex27ScatraType::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex27PoroType::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex27ThermoType::Instance().Name() << " "
      << DRT::ELEMENTS::So_nurbs27ThermoType::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex20ThermoType::Instance().Name() << " "
      << DRT::ELEMENTS::So_hex27PlastType::Instance().Name() << " "
      << DRT::ELEMENTS::So_sh8Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_sh8PlastType::Instance().Name() << " "
      << DRT::ELEMENTS::So_sh8p8Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_shw6Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_tet10Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_tet10PoroType::Instance().Name() << " "
      << DRT::ELEMENTS::So_tet10ScatraType::Instance().Name() << " "
      << DRT::ELEMENTS::So_tet4PlastType::Instance().Name() << " "
      << DRT::ELEMENTS::So_tet4Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_tet4PoroType::Instance().Name() << " "
      << DRT::ELEMENTS::So_tet4PoroP1Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_tet4ScatraType::Instance().Name() << " "
      << DRT::ELEMENTS::So_tet4PoroScatraType::Instance().Name() << " "
      << DRT::ELEMENTS::So_tet4PoroP1ScatraType::Instance().Name() << " "
      << DRT::ELEMENTS::So_tet4ThermoType::Instance().Name() << " "
      << DRT::ELEMENTS::So_tet4avType::Instance().Name() << " "
      << DRT::ELEMENTS::So_tet10ThermoType::Instance().Name() << " "
      << DRT::ELEMENTS::So_weg6Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_pyramid5Type::Instance().Name() << " "
      << DRT::ELEMENTS::So_pyramid5fbarType::Instance().Name() << " "
      << DRT::ELEMENTS::ArteryType::Instance().Name() << " "
      << DRT::ELEMENTS::RedAirwayType::Instance().Name() << " "
      << DRT::ELEMENTS::RedAcinusType::Instance().Name() << " "
      << DRT::ELEMENTS::RedInterAcinarDepType::Instance().Name() << " "
      << DRT::ELEMENTS::RedAirBloodScatraType::Instance().Name() << " "
      << DRT::ELEMENTS::RedAirBloodScatraLine3Type::Instance().Name() << " "
      << DRT::ELEMENTS::ConstraintElement2Type::Instance().Name() << " "
      << DRT::ELEMENTS::ConstraintElement3Type::Instance().Name() << " "
      << DRT::ELEMENTS::LubricationType::Instance().Name() << " "
      << DRT::ELEMENTS::PoroFluidMultiPhaseType::Instance().Name() << " "
      << DRT::ELEMENTS::TransportType::Instance().Name() << " "
      << DRT::ELEMENTS::ThermoType::Instance().Name() << " "
      << DRT::ELEMENTS::ElemagType::Instance().Name() << " "
      << DRT::ELEMENTS::ElemagDiffType::Instance().Name() << " "
      << DRT::ELEMENTS::ElemagBoundaryType::Instance().Name() << " "
      << DRT::ELEMENTS::ElemagDiffBoundaryType::Instance().Name() << " "
      << DRT::ELEMENTS::ElemagIntFaceType::Instance().Name() << " "
      << DRT::ELEMENTS::ElemagDiffIntFaceType::Instance().Name() << " "
      << MAT::Cnst_1d_artType::Instance().Name() << " " << MAT::AAAgasserType::Instance().Name()
      << " " << MAT::AAAneohookeType::Instance().Name() << " "
      << MAT::AAAneohooke_stoproType::Instance().Name() << " "
      << MAT::AAAraghavanvorp_damageType::Instance().Name() << " "
      << MAT::AAA_mixedeffectsType::Instance().Name() << " "
      << MAT::ArrheniusPVType::Instance().Name() << " " << MAT::ArrheniusSpecType::Instance().Name()
      << " " << MAT::ArrheniusTempType::Instance().Name() << " "
      << MAT::CarreauYasudaType::Instance().Name() << " "
      << MAT::ConstraintMixtureType::Instance().Name() << " "
      << MAT::ConstraintMixtureHistoryType::Instance().Name() << " "
      << MAT::CrystalPlasticityType::Instance().Name() << " "
      << MAT::ElastHyperType::Instance().Name() << " "
      << MAT::PlasticElastHyperType::Instance().Name() << " "
      << MAT::PlasticElastHyperVCUType::Instance().Name() << " "
      << MAT::ViscoElastHyperType::Instance().Name() << " " << MAT::FerEchPVType::Instance().Name()
      << " " << MAT::FluidPoroType::Instance().Name() << " "
      << MAT::FluidPoroSinglePhaseType::Instance().Name() << " "
      << MAT::FluidPoroSingleVolFracType::Instance().Name() << " "
      << MAT::FluidPoroVolFracPressureType::Instance().Name() << " "
      << MAT::FluidPoroSingleReactionType::Instance().Name() << " "
      << MAT::FluidPoroMultiPhaseType::Instance().Name() << " "
      << MAT::FluidPoroMultiPhaseReactionsType::Instance().Name() << " "
      << MAT::FourierIsoType::Instance().Name() << " "
      << MAT::GrowthVolumetricType::Instance().Name() << " "
      << MAT::Membrane_ElastHyperType::Instance().Name() << " "
      << MAT::Membrane_ActiveStrainType::Instance().Name() << " "
      << MAT::GrowthRemodel_ElastHyperType::Instance().Name() << " "
      << MAT::MixtureType::Instance().Name() << " " << MAT::HerschelBulkleyType::Instance().Name()
      << " " << MAT::IonType::Instance().Name() << " "
      << MAT::LinearDensityViscosityType::Instance().Name() << " "
      << MAT::WeaklyCompressibleFluidType::Instance().Name() << " "
      << MAT::MatListType::Instance().Name() << " " << MAT::MatListReactionsType::Instance().Name()
      << " " << MAT::MatListChemotaxisType::Instance().Name() << " "
      << MAT::MatListChemoReacType::Instance().Name() << " " << MAT::ElchMatType::Instance().Name()
      << " " << MAT::MicroMaterialType::Instance().Name() << " "
      << MAT::MixFracType::Instance().Name() << " " << MAT::ModPowerLawType::Instance().Name()
      << " " << MAT::MurnaghanTaitFluidType::Instance().Name() << " "
      << MAT::MyocardType::Instance().Name() << MAT::NewtonianFluidType::Instance().Name() << " "
      << MAT::StructPoroType::Instance().Name() << " "
      << MAT::StructPoroReactionType::Instance().Name() << " "
      << MAT::StructPoroReactionECMType::Instance().Name() << " "
      << MAT::ScalarDepInterpType::Instance().Name() << " " << MAT::ScatraMatType::Instance().Name()
      << " " << MAT::ScatraMatPoroECMType::Instance().Name() << " "
      << MAT::ScatraMatMultiPoroFluidType::Instance().Name() << " "
      << MAT::ScatraMatMultiPoroVolFracType::Instance().Name() << " "
      << MAT::ScatraMatMultiPoroSolidType::Instance().Name() << " "
      << MAT::ScatraMatMultiPoroTemperatureType::Instance().Name() << " "
      << MAT::StVenantKirchhoffType::Instance().Name() << " "
      << MAT::LinElast1DType::Instance().Name() << " "
      << MAT::LinElast1DGrowthType::Instance().Name() << " "
      << MAT::SutherlandType::Instance().Name() << " " << MAT::TempDepWaterType::Instance().Name()
      << " " << MAT::ThermoStVenantKirchhoffType::Instance().Name() << " "
      << MAT::ThermoPlasticLinElastType::Instance().Name() << " "
      << MAT::ViscoAnisotropicType::Instance().Name() << " "
      << MAT::ViscoNeoHookeType::Instance().Name() << " " << MAT::YoghurtType::Instance().Name()
      << " " << MAT::SpringType::Instance().Name() << " "
      << MAT::BeamElastHyperMaterialType<double>::Instance().Name() << " "
      << MAT::BeamElastHyperMaterialType<Sacado::Fad::DFad<double>>::Instance().Name() << " "
      << MAT::PlasticLinElastType::Instance().Name() << " " << MAT::RobinsonType::Instance().Name()
      << " " << MAT::DamageType::Instance().Name() << " "
      << MAT::ElectromagneticMatType::Instance().Name() << " "
      << MAT::Maxwell_0d_acinusType::Instance().Name() << " "
      << MAT::Maxwell_0d_acinusNeoHookeanType::Instance().Name() << " "
      << MAT::Maxwell_0d_acinusExponentialType::Instance().Name() << " "
      << MAT::Maxwell_0d_acinusDoubleExponentialType::Instance().Name() << " "
      << MAT::Maxwell_0d_acinusOgdenType::Instance().Name() << " "
      << MORTAR::NodeType::Instance().Name() << " " << MORTAR::ElementType::Instance().Name() << " "
      << CONTACT::NodeType::Instance().Name() << " " << CONTACT::FriNodeType::Instance().Name()
      << " " << CONTACT::ElementType::Instance().Name() << " "
      << BEAMINTERACTION::BeamLinkBeam3rLine2RigidJointedType::Instance().Name() << " "
      << BEAMINTERACTION::BeamLinkBeam3rLine2PinJointedType::Instance().Name() << " "
      << BEAMINTERACTION::BeamLinkTrussType::Instance().Name() << " "
      << PARTICLEENGINE::ParticleObjectType::Instance().Name() << " "
      << STRUMULTI::MicroStaticParObjectType::Instance().Name() << " ";
  }

  void AttachFunctionDefinitions(CORE::UTILS::FunctionManager& function_manager)
  {
    AddValidBuiltinFunctions(function_manager);
    STR::AddValidStructureFunctions(function_manager);
    FLD::AddValidFluidFunctions(function_manager);
    DRT::UTILS::AddValidCombustFunctions(function_manager);
    DRT::UTILS::AddValidXfluidFunctions(function_manager);
    AddValidLibraryFunctions(function_manager);
    POROMULTIPHASESCATRA::AddValidPoroFunctions(function_manager);
  }

}  // namespace

ModuleCallbacks GlobalLegacyModuleCallbacks()
{
  ModuleCallbacks callbacks;
  callbacks.RegisterParObjectTypes = RegisterParObjectTypes;
  callbacks.AttachFunctionDefinitions = AttachFunctionDefinitions;
  return callbacks;
}

FOUR_C_NAMESPACE_CLOSE
