/*!----------------------------------------------------------------------
\brief Test for the CUT Library
\file cut_test_bacigenerated_1910.cpp

\level 1

\maintainer Ager Christoph
*----------------------------------------------------------------------*/
// This test was automatically generated by CUT::OUTPUT::GmshElementCutTest(),
// as the cut crashed for this configuration!

#include <iostream>
#include <map>
#include <string>
#include <vector>

#include "cut_test_utils.H"

#include "../../src/drt_cut/cut_side.H"
#include "../../src/drt_cut/cut_meshintersection.H"
#include "../../src/drt_cut/cut_levelsetintersection.H"
#include "../../src/drt_cut/cut_combintersection.H"
#include "../../src/drt_cut/cut_tetmeshintersection.H"
#include "../../src/drt_cut/cut_options.H"
#include "../../src/drt_cut/cut_volumecell.H"

#include "../../src/drt_fem_general/drt_utils_local_connectivity_matrices.H"

void test_bacigenerated_1910()
{
  GEO::CUT::MeshIntersection intersection;
  intersection.GetOptions().Init_for_Cuttests();  // use full cln
  std::vector<int> nids;

  int sidecount = 0;
  std::vector<double> lsvs(8);
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0575201;
    tri3_xyze(1, 0) = -0.0154125;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2542);
    tri3_xyze(0, 1) = -0.0595492;
    tri3_xyze(1, 1) = -9.23291e-14;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2546);
    tri3_xyze(0, 2) = -0.0538414;
    tri3_xyze(1, 2) = -0.00708835;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-1);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0595492;
    tri3_xyze(1, 0) = -9.23291e-14;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2546);
    tri3_xyze(0, 1) = -0.05;
    tri3_xyze(1, 1) = 0;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2545);
    tri3_xyze(0, 2) = -0.0538414;
    tri3_xyze(1, 2) = -0.00708835;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-1);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.05;
    tri3_xyze(1, 0) = 0;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2545);
    tri3_xyze(0, 1) = -0.0482963;
    tri3_xyze(1, 1) = -0.012941;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2541);
    tri3_xyze(0, 2) = -0.0538414;
    tri3_xyze(1, 2) = -0.00708835;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-1);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0482963;
    tri3_xyze(1, 0) = -0.012941;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2541);
    tri3_xyze(0, 1) = -0.0575201;
    tri3_xyze(1, 1) = -0.0154125;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2542);
    tri3_xyze(0, 2) = -0.0538414;
    tri3_xyze(1, 2) = -0.00708835;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-1);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0575201;
    tri3_xyze(1, 0) = -0.0154125;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2542);
    tri3_xyze(0, 1) = -0.0816682;
    tri3_xyze(1, 1) = -0.0218829;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2549);
    tri3_xyze(0, 2) = -0.0708216;
    tri3_xyze(1, 2) = -0.00932385;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-5);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0816682;
    tri3_xyze(1, 0) = -0.0218829;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2549);
    tri3_xyze(0, 1) = -0.0845492;
    tri3_xyze(1, 1) = -1.49392e-13;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2551);
    tri3_xyze(0, 2) = -0.0708216;
    tri3_xyze(1, 2) = -0.00932385;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-5);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0845492;
    tri3_xyze(1, 0) = -1.49392e-13;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2551);
    tri3_xyze(0, 1) = -0.0595492;
    tri3_xyze(1, 1) = -9.23291e-14;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2546);
    tri3_xyze(0, 2) = -0.0708216;
    tri3_xyze(1, 2) = -0.00932385;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-5);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0595492;
    tri3_xyze(1, 0) = -9.23291e-14;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2546);
    tri3_xyze(0, 1) = -0.0575201;
    tri3_xyze(1, 1) = -0.0154125;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2542);
    tri3_xyze(0, 2) = -0.0708216;
    tri3_xyze(1, 2) = -0.00932385;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-5);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0515711;
    tri3_xyze(1, 0) = -0.0297746;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2582);
    tri3_xyze(0, 1) = -0.0732217;
    tri3_xyze(1, 1) = -0.0422746;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2585);
    tri3_xyze(0, 2) = -0.0659953;
    tri3_xyze(1, 2) = -0.0273361;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-6);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0732217;
    tri3_xyze(1, 0) = -0.0422746;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2585);
    tri3_xyze(0, 1) = -0.0816682;
    tri3_xyze(1, 1) = -0.0218829;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2549);
    tri3_xyze(0, 2) = -0.0659953;
    tri3_xyze(1, 2) = -0.0273361;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-6);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0816682;
    tri3_xyze(1, 0) = -0.0218829;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2549);
    tri3_xyze(0, 1) = -0.0575201;
    tri3_xyze(1, 1) = -0.0154125;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2542);
    tri3_xyze(0, 2) = -0.0659953;
    tri3_xyze(1, 2) = -0.0273361;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-6);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0575201;
    tri3_xyze(1, 0) = -0.0154125;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2542);
    tri3_xyze(0, 1) = -0.0515711;
    tri3_xyze(1, 1) = -0.0297746;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2582);
    tri3_xyze(0, 2) = -0.0659953;
    tri3_xyze(1, 2) = -0.0273361;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-6);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.05;
    tri3_xyze(1, 0) = 0;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2545);
    tri3_xyze(0, 1) = -0.0595492;
    tri3_xyze(1, 1) = -9.23291e-14;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2546);
    tri3_xyze(0, 2) = -0.0538414;
    tri3_xyze(1, 2) = 0.00708835;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-7);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0595492;
    tri3_xyze(1, 0) = -9.23291e-14;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2546);
    tri3_xyze(0, 1) = -0.0575201;
    tri3_xyze(1, 1) = 0.0154125;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2802);
    tri3_xyze(0, 2) = -0.0538414;
    tri3_xyze(1, 2) = 0.00708835;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-7);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0433013;
    tri3_xyze(1, 0) = -0.025;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2581);
    tri3_xyze(0, 1) = -0.0515711;
    tri3_xyze(1, 1) = -0.0297746;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2582);
    tri3_xyze(0, 2) = -0.0501722;
    tri3_xyze(1, 2) = -0.020782;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-2);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0515711;
    tri3_xyze(1, 0) = -0.0297746;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2582);
    tri3_xyze(0, 1) = -0.0575201;
    tri3_xyze(1, 1) = -0.0154125;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2542);
    tri3_xyze(0, 2) = -0.0501722;
    tri3_xyze(1, 2) = -0.020782;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-2);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0575201;
    tri3_xyze(1, 0) = -0.0154125;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2542);
    tri3_xyze(0, 1) = -0.0482963;
    tri3_xyze(1, 1) = -0.012941;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2541);
    tri3_xyze(0, 2) = -0.0501722;
    tri3_xyze(1, 2) = -0.020782;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-2);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0595492;
    tri3_xyze(1, 0) = 9.23291e-14;
    tri3_xyze(2, 0) = 0.829389;
    nids.push_back(2579);
    tri3_xyze(0, 1) = -0.05;
    tri3_xyze(1, 1) = 0;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2545);
    tri3_xyze(0, 2) = -0.0538414;
    tri3_xyze(1, 2) = 0.00708835;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-8);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0595492;
    tri3_xyze(1, 0) = -9.23291e-14;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2546);
    tri3_xyze(0, 1) = -0.0845492;
    tri3_xyze(1, 1) = -1.49392e-13;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2551);
    tri3_xyze(0, 2) = -0.0708216;
    tri3_xyze(1, 2) = 0.00932385;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-9);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0845492;
    tri3_xyze(1, 0) = -1.49392e-13;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2551);
    tri3_xyze(0, 1) = -0.0816682;
    tri3_xyze(1, 1) = 0.0218829;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2805);
    tri3_xyze(0, 2) = -0.0708216;
    tri3_xyze(1, 2) = 0.00932385;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-9);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0575201;
    tri3_xyze(1, 0) = 0.0154125;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2802);
    tri3_xyze(0, 1) = -0.0595492;
    tri3_xyze(1, 1) = -9.23291e-14;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2546);
    tri3_xyze(0, 2) = -0.0708216;
    tri3_xyze(1, 2) = 0.00932385;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-9);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0816682;
    tri3_xyze(1, 0) = -0.0218829;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2549);
    tri3_xyze(0, 1) = -0.111517;
    tri3_xyze(1, 1) = -0.0298809;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2553);
    tri3_xyze(0, 2) = -0.0982963;
    tri3_xyze(1, 2) = -0.012941;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-10);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.111517;
    tri3_xyze(1, 0) = -0.0298809;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2553);
    tri3_xyze(0, 1) = -0.115451;
    tri3_xyze(1, 1) = -1.49392e-13;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2555);
    tri3_xyze(0, 2) = -0.0982963;
    tri3_xyze(1, 2) = -0.012941;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-10);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.115451;
    tri3_xyze(1, 0) = -1.49392e-13;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2555);
    tri3_xyze(0, 1) = -0.0845492;
    tri3_xyze(1, 1) = -1.49392e-13;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2551);
    tri3_xyze(0, 2) = -0.0982963;
    tri3_xyze(1, 2) = -0.012941;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-10);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0845492;
    tri3_xyze(1, 0) = -1.49392e-13;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2551);
    tri3_xyze(0, 1) = -0.0816682;
    tri3_xyze(1, 1) = -0.0218829;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2549);
    tri3_xyze(0, 2) = -0.0982963;
    tri3_xyze(1, 2) = -0.012941;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-10);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0732217;
    tri3_xyze(1, 0) = -0.0422746;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2585);
    tri3_xyze(0, 1) = -0.0999834;
    tri3_xyze(1, 1) = -0.0577254;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2587);
    tri3_xyze(0, 2) = -0.0915976;
    tri3_xyze(1, 2) = -0.037941;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-11);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0999834;
    tri3_xyze(1, 0) = -0.0577254;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2587);
    tri3_xyze(0, 1) = -0.111517;
    tri3_xyze(1, 1) = -0.0298809;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2553);
    tri3_xyze(0, 2) = -0.0915976;
    tri3_xyze(1, 2) = -0.037941;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-11);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0482963;
    tri3_xyze(1, 0) = -0.012941;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2541);
    tri3_xyze(0, 1) = -0.0433013;
    tri3_xyze(1, 1) = -0.025;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2581);
    tri3_xyze(0, 2) = -0.0501722;
    tri3_xyze(1, 2) = -0.020782;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-2);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0482963;
    tri3_xyze(1, 0) = -0.012941;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2541);
    tri3_xyze(0, 1) = -0.05;
    tri3_xyze(1, 1) = 0;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2545);
    tri3_xyze(0, 2) = -0.0538414;
    tri3_xyze(1, 2) = -0.00708835;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-3);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.05;
    tri3_xyze(1, 0) = 0;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2545);
    tri3_xyze(0, 1) = -0.0595492;
    tri3_xyze(1, 1) = 9.23291e-14;
    tri3_xyze(2, 1) = 0.829389;
    nids.push_back(2579);
    tri3_xyze(0, 2) = -0.0538414;
    tri3_xyze(1, 2) = -0.00708835;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-3);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.111517;
    tri3_xyze(1, 0) = -0.0298809;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2553);
    tri3_xyze(0, 1) = -0.0816682;
    tri3_xyze(1, 1) = -0.0218829;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2549);
    tri3_xyze(0, 2) = -0.0915976;
    tri3_xyze(1, 2) = -0.037941;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-11);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0816682;
    tri3_xyze(1, 0) = -0.0218829;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2549);
    tri3_xyze(0, 1) = -0.0732217;
    tri3_xyze(1, 1) = -0.0422746;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2585);
    tri3_xyze(0, 2) = -0.0915976;
    tri3_xyze(1, 2) = -0.037941;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-11);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0845492;
    tri3_xyze(1, 0) = -1.49392e-13;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2551);
    tri3_xyze(0, 1) = -0.115451;
    tri3_xyze(1, 1) = -1.49392e-13;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2555);
    tri3_xyze(0, 2) = -0.0982963;
    tri3_xyze(1, 2) = 0.012941;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-12);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.115451;
    tri3_xyze(1, 0) = -1.49392e-13;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2555);
    tri3_xyze(0, 1) = -0.111517;
    tri3_xyze(1, 1) = 0.0298809;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2807);
    tri3_xyze(0, 2) = -0.0982963;
    tri3_xyze(1, 2) = 0.012941;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-12);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.111517;
    tri3_xyze(1, 0) = 0.0298809;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2807);
    tri3_xyze(0, 1) = -0.0816682;
    tri3_xyze(1, 1) = 0.0218829;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2805);
    tri3_xyze(0, 2) = -0.0982963;
    tri3_xyze(1, 2) = 0.012941;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-12);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0816682;
    tri3_xyze(1, 0) = 0.0218829;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2805);
    tri3_xyze(0, 1) = -0.0845492;
    tri3_xyze(1, 1) = -1.49392e-13;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2551);
    tri3_xyze(0, 2) = -0.0982963;
    tri3_xyze(1, 2) = 0.012941;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-12);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.111517;
    tri3_xyze(1, 0) = -0.0298809;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2553);
    tri3_xyze(0, 1) = -0.135665;
    tri3_xyze(1, 1) = -0.0363514;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2557);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = -0.0165581;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-13);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.135665;
    tri3_xyze(1, 0) = -0.0363514;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2557);
    tri3_xyze(0, 1) = -0.140451;
    tri3_xyze(1, 1) = -9.23291e-14;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2559);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = -0.0165581;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-13);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.140451;
    tri3_xyze(1, 0) = -9.23291e-14;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2559);
    tri3_xyze(0, 1) = -0.115451;
    tri3_xyze(1, 1) = -1.49392e-13;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2555);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = -0.0165581;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-13);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.115451;
    tri3_xyze(1, 0) = -1.49392e-13;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2555);
    tri3_xyze(0, 1) = -0.111517;
    tri3_xyze(1, 1) = -0.0298809;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2553);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = -0.0165581;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-13);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0999834;
    tri3_xyze(1, 0) = -0.0577254;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2587);
    tri3_xyze(0, 1) = -0.121634;
    tri3_xyze(1, 1) = -0.0702254;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2589);
    tri3_xyze(0, 2) = -0.1172;
    tri3_xyze(1, 2) = -0.0485458;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-14);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.121634;
    tri3_xyze(1, 0) = -0.0702254;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2589);
    tri3_xyze(0, 1) = -0.135665;
    tri3_xyze(1, 1) = -0.0363514;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2557);
    tri3_xyze(0, 2) = -0.1172;
    tri3_xyze(1, 2) = -0.0485458;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-14);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.135665;
    tri3_xyze(1, 0) = -0.0363514;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2557);
    tri3_xyze(0, 1) = -0.111517;
    tri3_xyze(1, 1) = -0.0298809;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2553);
    tri3_xyze(0, 2) = -0.1172;
    tri3_xyze(1, 2) = -0.0485458;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-14);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.111517;
    tri3_xyze(1, 0) = -0.0298809;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2553);
    tri3_xyze(0, 1) = -0.0999834;
    tri3_xyze(1, 1) = -0.0577254;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2587);
    tri3_xyze(0, 2) = -0.1172;
    tri3_xyze(1, 2) = -0.0485458;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-14);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.115451;
    tri3_xyze(1, 0) = -1.49392e-13;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2555);
    tri3_xyze(0, 1) = -0.140451;
    tri3_xyze(1, 1) = -9.23291e-14;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2559);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = 0.0165581;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-15);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.140451;
    tri3_xyze(1, 0) = -9.23291e-14;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2559);
    tri3_xyze(0, 1) = -0.135665;
    tri3_xyze(1, 1) = 0.0363514;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2809);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = 0.0165581;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-15);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.135665;
    tri3_xyze(1, 0) = 0.0363514;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2809);
    tri3_xyze(0, 1) = -0.111517;
    tri3_xyze(1, 1) = 0.0298809;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2807);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = 0.0165581;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-15);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.111517;
    tri3_xyze(1, 0) = 0.0298809;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2807);
    tri3_xyze(0, 1) = -0.115451;
    tri3_xyze(1, 1) = -1.49392e-13;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2555);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = 0.0165581;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-15);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.135665;
    tri3_xyze(1, 0) = -0.0363514;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2557);
    tri3_xyze(0, 1) = -0.144889;
    tri3_xyze(1, 1) = -0.0388229;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2561);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = -0.0187936;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-16);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.144889;
    tri3_xyze(1, 0) = -0.0388229;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2561);
    tri3_xyze(0, 1) = -0.15;
    tri3_xyze(1, 1) = 0;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2563);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = -0.0187936;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-16);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.15;
    tri3_xyze(1, 0) = 0;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2563);
    tri3_xyze(0, 1) = -0.140451;
    tri3_xyze(1, 1) = -9.23291e-14;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2559);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = -0.0187936;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-16);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.140451;
    tri3_xyze(1, 0) = -9.23291e-14;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2559);
    tri3_xyze(0, 1) = -0.135665;
    tri3_xyze(1, 1) = -0.0363514;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2557);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = -0.0187936;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-16);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.121634;
    tri3_xyze(1, 0) = -0.0702254;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2589);
    tri3_xyze(0, 1) = -0.129904;
    tri3_xyze(1, 1) = -0.075;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2591);
    tri3_xyze(0, 2) = -0.133023;
    tri3_xyze(1, 2) = -0.0550999;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-17);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.129904;
    tri3_xyze(1, 0) = -0.075;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2591);
    tri3_xyze(0, 1) = -0.144889;
    tri3_xyze(1, 1) = -0.0388229;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2561);
    tri3_xyze(0, 2) = -0.133023;
    tri3_xyze(1, 2) = -0.0550999;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-17);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.144889;
    tri3_xyze(1, 0) = -0.0388229;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2561);
    tri3_xyze(0, 1) = -0.135665;
    tri3_xyze(1, 1) = -0.0363514;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2557);
    tri3_xyze(0, 2) = -0.133023;
    tri3_xyze(1, 2) = -0.0550999;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-17);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.135665;
    tri3_xyze(1, 0) = -0.0363514;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2557);
    tri3_xyze(0, 1) = -0.121634;
    tri3_xyze(1, 1) = -0.0702254;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2589);
    tri3_xyze(0, 2) = -0.133023;
    tri3_xyze(1, 2) = -0.0550999;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-17);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.140451;
    tri3_xyze(1, 0) = -9.23291e-14;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2559);
    tri3_xyze(0, 1) = -0.15;
    tri3_xyze(1, 1) = 0;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2563);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = 0.0187936;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-18);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.15;
    tri3_xyze(1, 0) = 0;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2563);
    tri3_xyze(0, 1) = -0.144889;
    tri3_xyze(1, 1) = 0.0388229;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2811);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = 0.0187936;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-18);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.144889;
    tri3_xyze(1, 0) = 0.0388229;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2811);
    tri3_xyze(0, 1) = -0.135665;
    tri3_xyze(1, 1) = 0.0363514;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2809);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = 0.0187936;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-18);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.135665;
    tri3_xyze(1, 0) = 0.0363514;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2809);
    tri3_xyze(0, 1) = -0.140451;
    tri3_xyze(1, 1) = -9.23291e-14;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2559);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = 0.0187936;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-18);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.144889;
    tri3_xyze(1, 0) = -0.0388229;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2561);
    tri3_xyze(0, 1) = -0.135665;
    tri3_xyze(1, 1) = -0.0363514;
    tri3_xyze(2, 1) = 0.829389;
    nids.push_back(2565);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = -0.0187936;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-19);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.135665;
    tri3_xyze(1, 0) = -0.0363514;
    tri3_xyze(2, 0) = 0.829389;
    nids.push_back(2565);
    tri3_xyze(0, 1) = -0.140451;
    tri3_xyze(1, 1) = 9.23291e-14;
    tri3_xyze(2, 1) = 0.829389;
    nids.push_back(2567);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = -0.0187936;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-19);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.140451;
    tri3_xyze(1, 0) = 9.23291e-14;
    tri3_xyze(2, 0) = 0.829389;
    nids.push_back(2567);
    tri3_xyze(0, 1) = -0.15;
    tri3_xyze(1, 1) = 0;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2563);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = -0.0187936;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-19);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.15;
    tri3_xyze(1, 0) = 0;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2563);
    tri3_xyze(0, 1) = -0.144889;
    tri3_xyze(1, 1) = -0.0388229;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2561);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = -0.0187936;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-19);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.129904;
    tri3_xyze(1, 0) = -0.075;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2591);
    tri3_xyze(0, 1) = -0.121634;
    tri3_xyze(1, 1) = -0.0702254;
    tri3_xyze(2, 1) = 0.829389;
    nids.push_back(2593);
    tri3_xyze(0, 2) = -0.133023;
    tri3_xyze(1, 2) = -0.0550999;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-20);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.121634;
    tri3_xyze(1, 0) = -0.0702254;
    tri3_xyze(2, 0) = 0.829389;
    nids.push_back(2593);
    tri3_xyze(0, 1) = -0.135665;
    tri3_xyze(1, 1) = -0.0363514;
    tri3_xyze(2, 1) = 0.829389;
    nids.push_back(2565);
    tri3_xyze(0, 2) = -0.133023;
    tri3_xyze(1, 2) = -0.0550999;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-20);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.135665;
    tri3_xyze(1, 0) = -0.0363514;
    tri3_xyze(2, 0) = 0.829389;
    nids.push_back(2565);
    tri3_xyze(0, 1) = -0.144889;
    tri3_xyze(1, 1) = -0.0388229;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2561);
    tri3_xyze(0, 2) = -0.133023;
    tri3_xyze(1, 2) = -0.0550999;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-20);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.144889;
    tri3_xyze(1, 0) = -0.0388229;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2561);
    tri3_xyze(0, 1) = -0.129904;
    tri3_xyze(1, 1) = -0.075;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2591);
    tri3_xyze(0, 2) = -0.133023;
    tri3_xyze(1, 2) = -0.0550999;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-20);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.15;
    tri3_xyze(1, 0) = 0;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2563);
    tri3_xyze(0, 1) = -0.140451;
    tri3_xyze(1, 1) = 9.23291e-14;
    tri3_xyze(2, 1) = 0.829389;
    nids.push_back(2567);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = 0.0187936;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-21);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.140451;
    tri3_xyze(1, 0) = 9.23291e-14;
    tri3_xyze(2, 0) = 0.829389;
    nids.push_back(2567);
    tri3_xyze(0, 1) = -0.135665;
    tri3_xyze(1, 1) = 0.0363514;
    tri3_xyze(2, 1) = 0.829389;
    nids.push_back(2813);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = 0.0187936;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-21);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.135665;
    tri3_xyze(1, 0) = 0.0363514;
    tri3_xyze(2, 0) = 0.829389;
    nids.push_back(2813);
    tri3_xyze(0, 1) = -0.144889;
    tri3_xyze(1, 1) = 0.0388229;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2811);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = 0.0187936;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-21);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.144889;
    tri3_xyze(1, 0) = 0.0388229;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2811);
    tri3_xyze(0, 1) = -0.15;
    tri3_xyze(1, 1) = 0;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2563);
    tri3_xyze(0, 2) = -0.142751;
    tri3_xyze(1, 2) = 0.0187936;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-21);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.135665;
    tri3_xyze(1, 0) = -0.0363514;
    tri3_xyze(2, 0) = 0.829389;
    nids.push_back(2565);
    tri3_xyze(0, 1) = -0.111517;
    tri3_xyze(1, 1) = -0.0298809;
    tri3_xyze(2, 1) = 0.847553;
    nids.push_back(2569);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = -0.0165581;
    tri3_xyze(2, 2) = 0.838471;
    nids.push_back(-22);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.111517;
    tri3_xyze(1, 0) = -0.0298809;
    tri3_xyze(2, 0) = 0.847553;
    nids.push_back(2569);
    tri3_xyze(0, 1) = -0.115451;
    tri3_xyze(1, 1) = 1.49392e-13;
    tri3_xyze(2, 1) = 0.847553;
    nids.push_back(2571);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = -0.0165581;
    tri3_xyze(2, 2) = 0.838471;
    nids.push_back(-22);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.115451;
    tri3_xyze(1, 0) = 1.49392e-13;
    tri3_xyze(2, 0) = 0.847553;
    nids.push_back(2571);
    tri3_xyze(0, 1) = -0.140451;
    tri3_xyze(1, 1) = 9.23291e-14;
    tri3_xyze(2, 1) = 0.829389;
    nids.push_back(2567);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = -0.0165581;
    tri3_xyze(2, 2) = 0.838471;
    nids.push_back(-22);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.140451;
    tri3_xyze(1, 0) = 9.23291e-14;
    tri3_xyze(2, 0) = 0.829389;
    nids.push_back(2567);
    tri3_xyze(0, 1) = -0.135665;
    tri3_xyze(1, 1) = -0.0363514;
    tri3_xyze(2, 1) = 0.829389;
    nids.push_back(2565);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = -0.0165581;
    tri3_xyze(2, 2) = 0.838471;
    nids.push_back(-22);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.121634;
    tri3_xyze(1, 0) = -0.0702254;
    tri3_xyze(2, 0) = 0.829389;
    nids.push_back(2593);
    tri3_xyze(0, 1) = -0.0999834;
    tri3_xyze(1, 1) = -0.0577254;
    tri3_xyze(2, 1) = 0.847553;
    nids.push_back(2595);
    tri3_xyze(0, 2) = -0.1172;
    tri3_xyze(1, 2) = -0.0485458;
    tri3_xyze(2, 2) = 0.838471;
    nids.push_back(-23);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0999834;
    tri3_xyze(1, 0) = -0.0577254;
    tri3_xyze(2, 0) = 0.847553;
    nids.push_back(2595);
    tri3_xyze(0, 1) = -0.111517;
    tri3_xyze(1, 1) = -0.0298809;
    tri3_xyze(2, 1) = 0.847553;
    nids.push_back(2569);
    tri3_xyze(0, 2) = -0.1172;
    tri3_xyze(1, 2) = -0.0485458;
    tri3_xyze(2, 2) = 0.838471;
    nids.push_back(-23);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.111517;
    tri3_xyze(1, 0) = -0.0298809;
    tri3_xyze(2, 0) = 0.847553;
    nids.push_back(2569);
    tri3_xyze(0, 1) = -0.135665;
    tri3_xyze(1, 1) = -0.0363514;
    tri3_xyze(2, 1) = 0.829389;
    nids.push_back(2565);
    tri3_xyze(0, 2) = -0.1172;
    tri3_xyze(1, 2) = -0.0485458;
    tri3_xyze(2, 2) = 0.838471;
    nids.push_back(-23);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.135665;
    tri3_xyze(1, 0) = -0.0363514;
    tri3_xyze(2, 0) = 0.829389;
    nids.push_back(2565);
    tri3_xyze(0, 1) = -0.121634;
    tri3_xyze(1, 1) = -0.0702254;
    tri3_xyze(2, 1) = 0.829389;
    nids.push_back(2593);
    tri3_xyze(0, 2) = -0.1172;
    tri3_xyze(1, 2) = -0.0485458;
    tri3_xyze(2, 2) = 0.838471;
    nids.push_back(-23);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.140451;
    tri3_xyze(1, 0) = 9.23291e-14;
    tri3_xyze(2, 0) = 0.829389;
    nids.push_back(2567);
    tri3_xyze(0, 1) = -0.115451;
    tri3_xyze(1, 1) = 1.49392e-13;
    tri3_xyze(2, 1) = 0.847553;
    nids.push_back(2571);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = 0.0165581;
    tri3_xyze(2, 2) = 0.838471;
    nids.push_back(-24);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.115451;
    tri3_xyze(1, 0) = 1.49392e-13;
    tri3_xyze(2, 0) = 0.847553;
    nids.push_back(2571);
    tri3_xyze(0, 1) = -0.111517;
    tri3_xyze(1, 1) = 0.0298809;
    tri3_xyze(2, 1) = 0.847553;
    nids.push_back(2815);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = 0.0165581;
    tri3_xyze(2, 2) = 0.838471;
    nids.push_back(-24);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.135665;
    tri3_xyze(1, 0) = 0.0363514;
    tri3_xyze(2, 0) = 0.829389;
    nids.push_back(2813);
    tri3_xyze(0, 1) = -0.140451;
    tri3_xyze(1, 1) = 9.23291e-14;
    tri3_xyze(2, 1) = 0.829389;
    nids.push_back(2567);
    tri3_xyze(0, 2) = -0.125771;
    tri3_xyze(1, 2) = 0.0165581;
    tri3_xyze(2, 2) = 0.838471;
    nids.push_back(-24);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.111517;
    tri3_xyze(1, 0) = -0.0298809;
    tri3_xyze(2, 0) = 0.847553;
    nids.push_back(2569);
    tri3_xyze(0, 1) = -0.0816682;
    tri3_xyze(1, 1) = -0.0218829;
    tri3_xyze(2, 1) = 0.847553;
    nids.push_back(2573);
    tri3_xyze(0, 2) = -0.0982963;
    tri3_xyze(1, 2) = -0.012941;
    tri3_xyze(2, 2) = 0.847553;
    nids.push_back(-25);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0845492;
    tri3_xyze(1, 0) = 1.49392e-13;
    tri3_xyze(2, 0) = 0.847553;
    nids.push_back(2575);
    tri3_xyze(0, 1) = -0.115451;
    tri3_xyze(1, 1) = 1.49392e-13;
    tri3_xyze(2, 1) = 0.847553;
    nids.push_back(2571);
    tri3_xyze(0, 2) = -0.0982963;
    tri3_xyze(1, 2) = -0.012941;
    tri3_xyze(2, 2) = 0.847553;
    nids.push_back(-25);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.115451;
    tri3_xyze(1, 0) = 1.49392e-13;
    tri3_xyze(2, 0) = 0.847553;
    nids.push_back(2571);
    tri3_xyze(0, 1) = -0.111517;
    tri3_xyze(1, 1) = -0.0298809;
    tri3_xyze(2, 1) = 0.847553;
    nids.push_back(2569);
    tri3_xyze(0, 2) = -0.0982963;
    tri3_xyze(1, 2) = -0.012941;
    tri3_xyze(2, 2) = 0.847553;
    nids.push_back(-25);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0816682;
    tri3_xyze(1, 0) = -0.0218829;
    tri3_xyze(2, 0) = 0.847553;
    nids.push_back(2573);
    tri3_xyze(0, 1) = -0.111517;
    tri3_xyze(1, 1) = -0.0298809;
    tri3_xyze(2, 1) = 0.847553;
    nids.push_back(2569);
    tri3_xyze(0, 2) = -0.0915976;
    tri3_xyze(1, 2) = -0.037941;
    tri3_xyze(2, 2) = 0.847553;
    nids.push_back(-26);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.111517;
    tri3_xyze(1, 0) = -0.0298809;
    tri3_xyze(2, 0) = 0.847553;
    nids.push_back(2569);
    tri3_xyze(0, 1) = -0.0999834;
    tri3_xyze(1, 1) = -0.0577254;
    tri3_xyze(2, 1) = 0.847553;
    nids.push_back(2595);
    tri3_xyze(0, 2) = -0.0915976;
    tri3_xyze(1, 2) = -0.037941;
    tri3_xyze(2, 2) = 0.847553;
    nids.push_back(-26);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.115451;
    tri3_xyze(1, 0) = 1.49392e-13;
    tri3_xyze(2, 0) = 0.847553;
    nids.push_back(2571);
    tri3_xyze(0, 1) = -0.0845492;
    tri3_xyze(1, 1) = 1.49392e-13;
    tri3_xyze(2, 1) = 0.847553;
    nids.push_back(2575);
    tri3_xyze(0, 2) = -0.0982963;
    tri3_xyze(1, 2) = 0.012941;
    tri3_xyze(2, 2) = 0.847553;
    nids.push_back(-27);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.111517;
    tri3_xyze(1, 0) = 0.0298809;
    tri3_xyze(2, 0) = 0.847553;
    nids.push_back(2815);
    tri3_xyze(0, 1) = -0.115451;
    tri3_xyze(1, 1) = 1.49392e-13;
    tri3_xyze(2, 1) = 0.847553;
    nids.push_back(2571);
    tri3_xyze(0, 2) = -0.0982963;
    tri3_xyze(1, 2) = 0.012941;
    tri3_xyze(2, 2) = 0.847553;
    nids.push_back(-27);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0421076;
    tri3_xyze(1, 0) = -0.0421076;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2602);
    tri3_xyze(0, 1) = -0.0515711;
    tri3_xyze(1, 1) = -0.0297746;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2582);
    tri3_xyze(0, 2) = -0.0430838;
    tri3_xyze(1, 2) = -0.0330594;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-31);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0515711;
    tri3_xyze(1, 0) = -0.0297746;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2582);
    tri3_xyze(0, 1) = -0.0433013;
    tri3_xyze(1, 1) = -0.025;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2581);
    tri3_xyze(0, 2) = -0.0430838;
    tri3_xyze(1, 2) = -0.0330594;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-31);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0421076;
    tri3_xyze(1, 0) = -0.0421076;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2602);
    tri3_xyze(0, 1) = -0.0597853;
    tri3_xyze(1, 1) = -0.0597853;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2605);
    tri3_xyze(0, 2) = -0.0566714;
    tri3_xyze(1, 2) = -0.0434855;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-33);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0597853;
    tri3_xyze(1, 0) = -0.0597853;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2605);
    tri3_xyze(0, 1) = -0.0732217;
    tri3_xyze(1, 1) = -0.0422746;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2585);
    tri3_xyze(0, 2) = -0.0566714;
    tri3_xyze(1, 2) = -0.0434855;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-33);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0732217;
    tri3_xyze(1, 0) = -0.0422746;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2585);
    tri3_xyze(0, 1) = -0.0515711;
    tri3_xyze(1, 1) = -0.0297746;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2582);
    tri3_xyze(0, 2) = -0.0566714;
    tri3_xyze(1, 2) = -0.0434855;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-33);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0515711;
    tri3_xyze(1, 0) = -0.0297746;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2582);
    tri3_xyze(0, 1) = -0.0421076;
    tri3_xyze(1, 1) = -0.0421076;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2602);
    tri3_xyze(0, 2) = -0.0566714;
    tri3_xyze(1, 2) = -0.0434855;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-33);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0999834;
    tri3_xyze(1, 0) = -0.0577254;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2587);
    tri3_xyze(0, 1) = -0.0732217;
    tri3_xyze(1, 1) = -0.0422746;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2585);
    tri3_xyze(0, 2) = -0.0786566;
    tri3_xyze(1, 2) = -0.0603553;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-34);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0732217;
    tri3_xyze(1, 0) = -0.0422746;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2585);
    tri3_xyze(0, 1) = -0.0597853;
    tri3_xyze(1, 1) = -0.0597853;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2605);
    tri3_xyze(0, 2) = -0.0786566;
    tri3_xyze(1, 2) = -0.0603553;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-34);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0816361;
    tri3_xyze(1, 0) = -0.0816361;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2607);
    tri3_xyze(0, 1) = -0.0993137;
    tri3_xyze(1, 1) = -0.0993137;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2609);
    tri3_xyze(0, 2) = -0.100642;
    tri3_xyze(1, 2) = -0.0772252;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-35);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0993137;
    tri3_xyze(1, 0) = -0.0993137;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2609);
    tri3_xyze(0, 1) = -0.121634;
    tri3_xyze(1, 1) = -0.0702254;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2589);
    tri3_xyze(0, 2) = -0.100642;
    tri3_xyze(1, 2) = -0.0772252;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-35);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.121634;
    tri3_xyze(1, 0) = -0.0702254;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2589);
    tri3_xyze(0, 1) = -0.0999834;
    tri3_xyze(1, 1) = -0.0577254;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2587);
    tri3_xyze(0, 2) = -0.100642;
    tri3_xyze(1, 2) = -0.0772252;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-35);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0999834;
    tri3_xyze(1, 0) = -0.0577254;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2587);
    tri3_xyze(0, 1) = -0.0816361;
    tri3_xyze(1, 1) = -0.0816361;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2607);
    tri3_xyze(0, 2) = -0.100642;
    tri3_xyze(1, 2) = -0.0772252;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-35);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0993137;
    tri3_xyze(1, 0) = -0.0993137;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2609);
    tri3_xyze(0, 1) = -0.106066;
    tri3_xyze(1, 1) = -0.106066;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2611);
    tri3_xyze(0, 2) = -0.114229;
    tri3_xyze(1, 2) = -0.0876513;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-36);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.106066;
    tri3_xyze(1, 0) = -0.106066;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2611);
    tri3_xyze(0, 1) = -0.129904;
    tri3_xyze(1, 1) = -0.075;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2591);
    tri3_xyze(0, 2) = -0.114229;
    tri3_xyze(1, 2) = -0.0876513;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-36);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.129904;
    tri3_xyze(1, 0) = -0.075;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2591);
    tri3_xyze(0, 1) = -0.121634;
    tri3_xyze(1, 1) = -0.0702254;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2589);
    tri3_xyze(0, 2) = -0.114229;
    tri3_xyze(1, 2) = -0.0876513;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-36);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.121634;
    tri3_xyze(1, 0) = -0.0702254;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2589);
    tri3_xyze(0, 1) = -0.0993137;
    tri3_xyze(1, 1) = -0.0993137;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2609);
    tri3_xyze(0, 2) = -0.114229;
    tri3_xyze(1, 2) = -0.0876513;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-36);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.121634;
    tri3_xyze(1, 0) = -0.0702254;
    tri3_xyze(2, 0) = 0.829389;
    nids.push_back(2593);
    tri3_xyze(0, 1) = -0.129904;
    tri3_xyze(1, 1) = -0.075;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2591);
    tri3_xyze(0, 2) = -0.114229;
    tri3_xyze(1, 2) = -0.0876513;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-37);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.129904;
    tri3_xyze(1, 0) = -0.075;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2591);
    tri3_xyze(0, 1) = -0.106066;
    tri3_xyze(1, 1) = -0.106066;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2611);
    tri3_xyze(0, 2) = -0.114229;
    tri3_xyze(1, 2) = -0.0876513;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-37);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0816682;
    tri3_xyze(1, 0) = 0.0218829;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2805);
    tri3_xyze(0, 1) = -0.111517;
    tri3_xyze(1, 1) = 0.0298809;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2807);
    tri3_xyze(0, 2) = -0.0915976;
    tri3_xyze(1, 2) = 0.037941;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-144);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.111517;
    tri3_xyze(1, 0) = 0.0298809;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2807);
    tri3_xyze(0, 1) = -0.0999834;
    tri3_xyze(1, 1) = 0.0577254;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2827);
    tri3_xyze(0, 2) = -0.0915976;
    tri3_xyze(1, 2) = 0.037941;
    tri3_xyze(2, 2) = 0.752447;
    nids.push_back(-144);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.111517;
    tri3_xyze(1, 0) = 0.0298809;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2807);
    tri3_xyze(0, 1) = -0.135665;
    tri3_xyze(1, 1) = 0.0363514;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2809);
    tri3_xyze(0, 2) = -0.1172;
    tri3_xyze(1, 2) = 0.0485458;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-145);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.135665;
    tri3_xyze(1, 0) = 0.0363514;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2809);
    tri3_xyze(0, 1) = -0.121634;
    tri3_xyze(1, 1) = 0.0702254;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2829);
    tri3_xyze(0, 2) = -0.1172;
    tri3_xyze(1, 2) = 0.0485458;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-145);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.121634;
    tri3_xyze(1, 0) = 0.0702254;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2829);
    tri3_xyze(0, 1) = -0.0999834;
    tri3_xyze(1, 1) = 0.0577254;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2827);
    tri3_xyze(0, 2) = -0.1172;
    tri3_xyze(1, 2) = 0.0485458;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-145);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.0999834;
    tri3_xyze(1, 0) = 0.0577254;
    tri3_xyze(2, 0) = 0.752447;
    nids.push_back(2827);
    tri3_xyze(0, 1) = -0.111517;
    tri3_xyze(1, 1) = 0.0298809;
    tri3_xyze(2, 1) = 0.752447;
    nids.push_back(2807);
    tri3_xyze(0, 2) = -0.1172;
    tri3_xyze(1, 2) = 0.0485458;
    tri3_xyze(2, 2) = 0.761529;
    nids.push_back(-145);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.135665;
    tri3_xyze(1, 0) = 0.0363514;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2809);
    tri3_xyze(0, 1) = -0.144889;
    tri3_xyze(1, 1) = 0.0388229;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2811);
    tri3_xyze(0, 2) = -0.133023;
    tri3_xyze(1, 2) = 0.0550999;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-146);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.144889;
    tri3_xyze(1, 0) = 0.0388229;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2811);
    tri3_xyze(0, 1) = -0.129904;
    tri3_xyze(1, 1) = 0.075;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2831);
    tri3_xyze(0, 2) = -0.133023;
    tri3_xyze(1, 2) = 0.0550999;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-146);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.121634;
    tri3_xyze(1, 0) = 0.0702254;
    tri3_xyze(2, 0) = 0.770611;
    nids.push_back(2829);
    tri3_xyze(0, 1) = -0.135665;
    tri3_xyze(1, 1) = 0.0363514;
    tri3_xyze(2, 1) = 0.770611;
    nids.push_back(2809);
    tri3_xyze(0, 2) = -0.133023;
    tri3_xyze(1, 2) = 0.0550999;
    tri3_xyze(2, 2) = 0.785305;
    nids.push_back(-146);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.144889;
    tri3_xyze(1, 0) = 0.0388229;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2811);
    tri3_xyze(0, 1) = -0.135665;
    tri3_xyze(1, 1) = 0.0363514;
    tri3_xyze(2, 1) = 0.829389;
    nids.push_back(2813);
    tri3_xyze(0, 2) = -0.133023;
    tri3_xyze(1, 2) = 0.0550999;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-147);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }
  {
    Epetra_SerialDenseMatrix tri3_xyze(3, 3);

    nids.clear();
    tri3_xyze(0, 0) = -0.129904;
    tri3_xyze(1, 0) = 0.075;
    tri3_xyze(2, 0) = 0.8;
    nids.push_back(2831);
    tri3_xyze(0, 1) = -0.144889;
    tri3_xyze(1, 1) = 0.0388229;
    tri3_xyze(2, 1) = 0.8;
    nids.push_back(2811);
    tri3_xyze(0, 2) = -0.133023;
    tri3_xyze(1, 2) = 0.0550999;
    tri3_xyze(2, 2) = 0.814695;
    nids.push_back(-147);
    intersection.AddCutSide(++sidecount, nids, tri3_xyze, DRT::Element::tri3);
  }



  {
    Epetra_SerialDenseMatrix hex8_xyze(3, 8);

    nids.clear();
    hex8_xyze(0, 0) = -0.1;
    hex8_xyze(1, 0) = -0.05;
    hex8_xyze(2, 0) = 0.75;
    nids.push_back(1896);
    hex8_xyze(0, 1) = -0.1;
    hex8_xyze(1, 1) = 0;
    hex8_xyze(2, 1) = 0.75;
    nids.push_back(1897);
    hex8_xyze(0, 2) = -0.15;
    hex8_xyze(1, 2) = 0;
    hex8_xyze(2, 2) = 0.75;
    nids.push_back(1908);
    hex8_xyze(0, 3) = -0.15;
    hex8_xyze(1, 3) = -0.05;
    hex8_xyze(2, 3) = 0.75;
    nids.push_back(1907);
    hex8_xyze(0, 4) = -0.1;
    hex8_xyze(1, 4) = -0.05;
    hex8_xyze(2, 4) = 0.8;
    nids.push_back(2017);
    hex8_xyze(0, 5) = -0.1;
    hex8_xyze(1, 5) = 0;
    hex8_xyze(2, 5) = 0.8;
    nids.push_back(2018);
    hex8_xyze(0, 6) = -0.15;
    hex8_xyze(1, 6) = 0;
    hex8_xyze(2, 6) = 0.8;
    nids.push_back(2029);
    hex8_xyze(0, 7) = -0.15;
    hex8_xyze(1, 7) = -0.05;
    hex8_xyze(2, 7) = 0.8;
    nids.push_back(2028);

    intersection.AddElement(1910, nids, hex8_xyze, DRT::Element::hex8);
  }



  intersection.Status();

  intersection.CutTest_Cut(
      true, INPAR::CUT::VCellGaussPts_DirectDivergence, INPAR::CUT::BCellGaussPts_Tessellation);
  intersection.Cut_Finalize(true, INPAR::CUT::VCellGaussPts_DirectDivergence,
      INPAR::CUT::BCellGaussPts_Tessellation, false, true);
}
