/*!----------------------------------------------------------------------

\file invana_cal_drt.H

\brief Start routines for the inverse analysis

<pre>
\level 3
\maintainer Sebastian Kehl
            kehl@mhpc.mw.tum.de
            http://www.mhpc.mw.tum.de
            089 - 289-10361
</pre>

*----------------------------------------------------------------------*/

#include "Epetra_MpiComm.h"
#include "Epetra_Time.h"
#include "Teuchos_RCP.hpp"

#ifndef INVANA_CAL_H
#define INVANA_CAL_H


void invana_cal();

#endif /* #ifndef INVANA_CAL_H */
