/*----------------------------------------------------------------------*/
/*! \file
 \brief entry point (global control routine) for poroelasticity multiphase flow

   \level 3

 *----------------------------------------------------------------------*/

#ifndef POROMULTIPHASE_DYN_H
#define POROMULTIPHASE_DYN_H

/*! entry point for the solution of poro multiphase problems problems */
void poromultiphase_dyn(int restart /* do we have to perform a restart?  */
);



#endif  // POROMULTIPHASE_DYN_H
