name: Download 4C Build
description: Downloads the 4C build from an artifact based on the upload_4C_build-action
inputs:
  build-job:
    description: Name of the build-job
    required: true
runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.build-job }}-4C-build
        path: ${{ github.workspace }}
    - name: Extract 4C build
      shell: bash
      run: |
        tar -xf $GITHUB_WORKSPACE/4C_build.tar -C /
        rm $GITHUB_WORKSPACE/4C_build.tar
