function(baci_add_dependency target)
  get_target_property(_target_type ${target} TYPE)
  if(${_target_type} STREQUAL INTERFACE_LIBRARY)
    target_link_libraries(${target} INTERFACE ${ARGN})
  else()
    target_link_libraries(${target} PUBLIC ${ARGN})
  endif()
endfunction()
