#!/bin/bash

# This file is part of 4C multiphysics licensed under the
# GNU Lesser General Public License v3.0 or later.
#
# See the LICENSE.md file in the top-level for license information.
#
# SPDX-License-Identifier: LGPL-3.0-or-later

# Exit the script at the first failure
set -e

# set the field separator to new line
IFS=$'\n'

# test all changed files
for file in "$@"
do
# check if there are non-ascii characters in the file (excluding *.md files)
  non_ascii_chars=$(LC_ALL=C sed 's/[\x00-\x7F]//g' "$file" | sort -u | tr -d '\n')
  if [ -n "$non_ascii_chars" ]; then
    cnt=${#non_ascii_chars}
    for ((i=0; i < cnt; i++)); do
      char=${non_ascii_chars:$i:1}
      non_ascii_error+="${file} contains non-ascii character '$char'\n"
    done
  fi
done

# printout for non-ascii characters
if [ ! -z "$non_ascii_error" ]
then
printf "\n"
printf "The following file(s) contain non-ascii characters:\n"
printf "\n"
printf $non_ascii_error
printf "\n"
echo "--> Please remove those non-ascii characters"
exit 1
fi

exit 0
