/*!----------------------------------------------------------------------
\file volmortar_defines.H

<pre>
Maintainer: Philipp Farah
            farah@lnm.mw.tum.de
            http://www.lnm.mw.tum.de
            089 - 289-15257
</pre>

*----------------------------------------------------------------------*/

#ifndef VOLMORTAR_DEFINES_H_
#define VOLMORTAR_DEFINES_H_

/************************************************************************/
/* Mortar algorithm parameters                                          */
/************************************************************************/

// MORTAR INTEGRATION
#define VOLMORTARINTTOL 0.0       /* tolerance for assembling gp-values*/


#endif /* VOLMORTAR_DEFINES_H_ */
