/*--------------------------------------------------------------------------*/
/*!
\file ehl_dyn.H

\brief dummy

<pre>
Maintainer: Andy Wirtz
            wirtz@lnm.mw.tum.de
            http://www.lnm.mw.tum.de
            089-289-15270
</pre>
*/
/*--------------------------------------------------------------------------*/
#ifndef SRC_DRT_EHL_EHL_DYN_H_
#define SRC_DRT_EHL_EHL_DYN_H_


/*! entry point for the solution of EHL problems */
void ehl_dyn(
    int restart        /* do we have to perform a restart?  */
    );


#endif /* SRC_DRT_EHL_EHL_DYN_H_ */
