
all: post_gid_txt

# ignore the binary gid format
# it doesn't seem to work any more and is not worth the trouble
#post_gid:
#	cd ../.. && $(MAKE) post_gid

post_gid_txt:
	cd ../.. && $(MAKE) post_gid_txt

clean:
	cd ../.. && $(MAKE) clean
