/*----------------------------------------------------------------------*/
/*! \file

\brief Implementation of registration of parallel objects

\level 1


*/
/*----------------------------------------------------------------------*/

#include <string>
#include <iostream>

#include "drt_parobjectregister.H"

#include "drt_control_point.H"
#include "beam3.H"
#include "beam3r.H"
#include "beam3eb.H"
#include "beam3k.H"
#include "discsh3.H"
#include "rigidsphere.H"
#include "truss3.H"
#include "truss3_scatra.H"
#include "torsion3.H"
#include "shell8.H"
#include "shell8_scatra.H"
#include "membrane_eletypes.H"
#include "membrane_scatra_eletypes.H"
#include "lubrication_ele.H"
#include "scatra_ele.H"
#include "porofluidmultiphase_ele.H"
#include "fluid_ele.H"
#include "fluid_ele_poro.H"
#include "fluid_ele_immersed.H"
#include "fluid_ele_xwall.H"
#include "fluid_ele_hdg.H"
#include "fluid_ele_hdg_weak_comp.H"
#include "ale2.H"
#include "ale2_nurbs.H"
#include "ale3.H"
#include "ale3_nurbs.H"
#include "bele3.H"
#include "vele3.H"
#include "bele2.H"
#include "constraint_element2.H"
#include "constraint_element3.H"
#include "wall1.H"
#include "wall1_nurbs.H"
#include "wall1_poro_eletypes.H"
#include "wall1_poro_p1_eletypes.H"
#include "wall1_scatra.H"
#include "wall1_poro_scatra_eletypes.H"
#include "wall1_poro_p1_scatra_eletypes.H"
#include "so_hex8.H"
#include "so_hex18.H"
#include "so_sh18.H"
#include "so_hex20.H"
#include "so_hex27.H"
#include "so_nurbs27.H"
#include "so_sh8.H"
#include "so_sh8p8.H"
#include "so_tet4.H"
#include "so_tet4av.H"
#include "so_nstet.H"
#include "so_nstet5.H"
#include "so_tet10.H"
#include "so_weg6.H"
#include "so_pyramid5.H"
#include "so_shw6.H"
#include "so_hex8p1j1.H"
#include "so_hex8fbar.H"
#include "so_pyramid5fbar.H"
#include "so3_poro_eletypes.H"
#include "so3_poro_p1_eletypes.H"
#include "so3_scatra_eletypes.H"
#include "so3_poro_scatra_eletypes.H"
#include "so3_poro_p1_scatra_eletypes.H"
#include "so3_thermo_eletypes.H"
#include "so3_ssn_plast_eletypes.H"
#include "so3_ssn_plast_sosh18.H"
#include "so3_ssn_plast_sosh8.H"
#include "thermo_element.H"
#include "newtonianfluid.H"
#include "stvenantkirchhoff.H"
#include "thermostvenantkirchhoff.H"
#include "thermoplasticlinelast.H"
#include "micromaterial.H"
#include "aaaneohooke.H"
#include "aaaneohooke_stopro.H"
#include "aaaraghavanvorp_damage.H"
#include "aaa_mixedeffects.H"
#include "aaagasser.H"
#include "visconeohooke.H"
#include "viscoanisotropic.H"
#include "scalardepinterp.H"
#include "scatra_mat.H"
#include "scatra_mat_poro_ecm.H"
#include "scatra_mat_multiporo.H"
#include "myocard.H"
#include "ion.H"
#include "lin_elast_1D.H"
#include "mixfrac.H"
#include "sutherland.H"
#include "fluid_murnaghantait.H"
#include "fluid_linear_density_viscosity.H"
#include "fluid_weakly_compressible.H"
#include "tempdepwater.H"
#include "arrhenius_spec.H"
#include "arrhenius_temp.H"
#include "arrhenius_pv.H"
#include "ferech_pv.H"
#include "carreauyasuda.H"
#include "modpowerlaw.H"
#include "herschelbulkley.H"
#include "yoghurt.H"
#include "matlist.H"
#include "matlist_reactions.H"
#include "matlist_chemotaxis.H"
#include "matlist_chemoreac.H"
#include "elchmat.H"
#include "elasthyper.H"
#include "plasticelasthyper.H"
#include "plastic_VarConstUpdate.H"
#include "viscoelasthyper.H"
#include "cnst_1d_art.H"
#include "fourieriso.H"
#include "membrane_elasthyper.H"
#include "membrane_active_strain.H"
#include "growthremodel_elasthyper.H"
#include "mixture_elasthyper.H"
#include "constraintmixture.H"
#include "constraintmixture_history.H"
#include "crystal_plasticity.H"
#include "plasticlinelast.H"
#include "robinson.H"
#include "damage.H"
#include "spring.H"
#include "beam_elasthyper.H"
#include "optimization_density.H"
#include "structporo.H"
#include "structporo_reaction.H"
#include "structporo_reaction_ecm.H"
#include "fluidporo.H"
#include "fluidporo_singlephase.H"
#include "fluidporo_multiphase.H"
#include "fluidporo_multiphase_reactions.H"
#include "fluidporo_multiphase_singlereaction.H"
#include "electromagnetic.H"
#include "mortar_node.H"
#include "mortar_element.H"
#include "contact_node.H"
#include "friction_node.H"
#include "contact_element.H"
#include "artery.H"
#include "red_airway.H"
#include "topopt_optimizer_ele.H"
#include "elemag_ele.H"
#include "elemag_diff_ele.H"
#include "beam_link_beam3r_line2_pinjointed.H"
#include "beam_link_beam3r_line2_rigidjointed.H"
#include "beam_link_truss.H"
#include "activefiber.H"
#include "immersed_node.H"
#include "maxwell_0d_acinus.H"
#include "maxwell_0d_acinus_NeoHookean.H"
#include "maxwell_0d_acinus_Exponential.H"
#include "maxwell_0d_acinus_DoubleExponential.H"
#include "maxwell_0d_acinus_Ogden.H"
#include "particle_data.H"
#include "crosslinker_node.H"
#include "drt_meshfree_multibin.H"
#include "growth.H"
#include "particle_object.H"

std::string DRT::ParObjectList()
{
  std::stringstream s;

  s << DRT::ContainerType::Instance().Name() << " " << DRT::ConditionObjectType::Instance().Name()
    << " " << DRT::NodeType::Instance().Name() << " "
    << DRT::NURBS::ControlPointType::Instance().Name() << " "
    << IMMERSED::ImmersedNodeType::Instance().Name() << " "
    << CROSSLINKING::CrosslinkerNodeType::Instance().Name() << " "
    << DRT::MESHFREE::MeshfreeMultiBinType::Instance().Name() << " "
    << DRT::ELEMENTS::Beam3Type::Instance().Name() << " "
    << DRT::ELEMENTS::Beam3rType::Instance().Name() << " "
    << DRT::ELEMENTS::Beam3ebType::Instance().Name() << " "
    << DRT::ELEMENTS::Beam3kType::Instance().Name() << " "
    << DRT::ELEMENTS::DiscSh3Type::Instance().Name() << " "
    << DRT::ELEMENTS::RigidsphereType::Instance().Name() << " "
    << DRT::ELEMENTS::Truss3Type::Instance().Name() << " "
    << DRT::ELEMENTS::Truss3ScatraType::Instance().Name() << " "
    << DRT::ELEMENTS::Torsion3Type::Instance().Name() << " "
    << DRT::ELEMENTS::Shell8Type::Instance().Name() << " "
    << DRT::ELEMENTS::Shell8ScatraType::Instance().Name() << " "
    << DRT::ELEMENTS::Membrane_tri3Type::Instance().Name() << " "
    << DRT::ELEMENTS::Membrane_tri6Type::Instance().Name() << " "
    << DRT::ELEMENTS::Membrane_quad4Type::Instance().Name() << " "
    << DRT::ELEMENTS::Membrane_quad9Type::Instance().Name() << " "
    << DRT::ELEMENTS::MembraneScatra_tri3Type::Instance().Name() << " "
    << DRT::ELEMENTS::MembraneScatra_tri6Type::Instance().Name() << " "
    << DRT::ELEMENTS::MembraneScatra_quad4Type::Instance().Name() << " "
    << DRT::ELEMENTS::MembraneScatra_quad9Type::Instance().Name() << " "
    << DRT::ELEMENTS::Wall1Type::Instance().Name() << " "
    << DRT::ELEMENTS::WallTri3PoroType::Instance().Name() << " "
    << DRT::ELEMENTS::WallTri3PoroP1Type::Instance().Name() << " "
    << DRT::ELEMENTS::WallQuad4PoroType::Instance().Name() << " "
    << DRT::ELEMENTS::WallQuad4PoroP1Type::Instance().Name() << " "
    << DRT::ELEMENTS::WallQuad9PoroType::Instance().Name() << " "
    << DRT::ELEMENTS::WallQuad9PoroP1Type::Instance().Name() << " "
    << DRT::ELEMENTS::WallNurbs4PoroType::Instance().Name() << " "
    << DRT::ELEMENTS::WallNurbs9PoroType::Instance().Name() << " "
    << DRT::ELEMENTS::NURBS::Wall1NurbsType::Instance().Name() << " "
    << DRT::ELEMENTS::Wall1ScatraType::Instance().Name() << " "
    << DRT::ELEMENTS::WallQuad4PoroScatraType::Instance().Name() << " "
    << DRT::ELEMENTS::WallQuad4PoroP1ScatraType::Instance().Name() << " "
    << DRT::ELEMENTS::FluidType::Instance().Name() << " "
    << DRT::ELEMENTS::FluidXWallType::Instance().Name() << " "
    << DRT::ELEMENTS::FluidXWallBoundaryType::Instance().Name() << " "
    << DRT::ELEMENTS::FluidTypeImmersed::Instance().Name() << " "
    << DRT::ELEMENTS::FluidPoroEleType::Instance().Name() << " "
    << DRT::ELEMENTS::FluidHDGType::Instance().Name() << " "
    << DRT::ELEMENTS::FluidHDGWeakCompType::Instance().Name() << " "
    << DRT::ELEMENTS::FluidBoundaryType::Instance().Name() << " "
    << DRT::ELEMENTS::FluidPoroBoundaryType::Instance().Name() << " "
    << DRT::ELEMENTS::Ale3Type::Instance().Name() << " "
    << DRT::ELEMENTS::NURBS::Ale3_NurbsType::Instance().Name() << " "
    << DRT::ELEMENTS::Ale2Type::Instance().Name() << " "
    << DRT::ELEMENTS::NURBS::Ale2_NurbsType::Instance().Name() << " "
    << DRT::ELEMENTS::Bele2Type::Instance().Name() << " "
    << DRT::ELEMENTS::Bele3Type::Instance().Name() << " "
    << DRT::ELEMENTS::Vele3Type::Instance().Name() << " "
    << DRT::ELEMENTS::NStetType::Instance().Name() << " "
    << DRT::ELEMENTS::NStet5Type::Instance().Name() << " "
    << DRT::ELEMENTS::NURBS::So_nurbs27Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_nurbs27PoroType::Instance().Name()
    << " "
    //    << DRT::ELEMENTS::PtetType::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex18Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_sh18Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_sh18PlastType::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex8Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_Hex8P1J1Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex8fbarType::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex8fbarScatraType::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex8fbarThermoType::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex8PoroType::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex8PoroP1Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex8ScatraType::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex8ThermoType::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex8PlastType::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex8Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex20Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex27Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex27ScatraType::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex27PoroType::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex27ThermoType::Instance().Name() << " "
    << DRT::ELEMENTS::So_nurbs27ThermoType::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex20ThermoType::Instance().Name() << " "
    << DRT::ELEMENTS::So_hex27PlastType::Instance().Name() << " "
    << DRT::ELEMENTS::So_sh8Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_sh8PlastType::Instance().Name() << " "
    << DRT::ELEMENTS::So_sh8p8Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_shw6Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_tet10Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_tet10PoroType::Instance().Name() << " "
    << DRT::ELEMENTS::So_tet10ScatraType::Instance().Name() << " "
    << DRT::ELEMENTS::So_tet4PlastType::Instance().Name() << " "
    << DRT::ELEMENTS::So_tet4Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_tet4PoroType::Instance().Name() << " "
    << DRT::ELEMENTS::So_tet4PoroP1Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_tet4ScatraType::Instance().Name() << " "
    << DRT::ELEMENTS::So_tet4PoroScatraType::Instance().Name() << " "
    << DRT::ELEMENTS::So_tet4PoroP1ScatraType::Instance().Name() << " "
    << DRT::ELEMENTS::So_tet4ThermoType::Instance().Name() << " "
    << DRT::ELEMENTS::So_tet4avType::Instance().Name() << " "
    << DRT::ELEMENTS::So_tet10ThermoType::Instance().Name() << " "
    << DRT::ELEMENTS::So_weg6Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_pyramid5Type::Instance().Name() << " "
    << DRT::ELEMENTS::So_pyramid5fbarType::Instance().Name() << " "
    << DRT::ELEMENTS::ArteryType::Instance().Name() << " "
    << DRT::ELEMENTS::RedAirwayType::Instance().Name() << " "
    << DRT::ELEMENTS::RedAcinusType::Instance().Name() << " "
    << DRT::ELEMENTS::RedInterAcinarDepType::Instance().Name() << " "
    << DRT::ELEMENTS::RedAirBloodScatraType::Instance().Name() << " "
    << DRT::ELEMENTS::RedAirBloodScatraLine3Type::Instance().Name() << " "
    << DRT::ELEMENTS::ConstraintElement2Type::Instance().Name() << " "
    << DRT::ELEMENTS::ConstraintElement3Type::Instance().Name() << " "
    << DRT::ELEMENTS::LubricationType::Instance().Name() << " "
    << DRT::ELEMENTS::PoroFluidMultiPhaseType::Instance().Name() << " "
    << DRT::ELEMENTS::TransportType::Instance().Name() << " "
    << DRT::ELEMENTS::TopOptType::Instance().Name() << " "
    << DRT::ELEMENTS::ThermoType::Instance().Name() << " "
    << DRT::ELEMENTS::ElemagType::Instance().Name() << " "
    << DRT::ELEMENTS::ElemagDiffType::Instance().Name() << " "
    << DRT::ELEMENTS::ElemagBoundaryType::Instance().Name() << " "
    << DRT::ELEMENTS::ElemagDiffBoundaryType::Instance().Name() << " "
    << DRT::ELEMENTS::ElemagIntFaceType::Instance().Name() << " "
    << DRT::ELEMENTS::ElemagDiffIntFaceType::Instance().Name() << " "
    << MAT::Cnst_1d_artType::Instance().Name() << " " << MAT::AAAgasserType::Instance().Name()
    << " " << MAT::AAAneohookeType::Instance().Name() << " "
    << MAT::AAAneohooke_stoproType::Instance().Name() << " "
    << MAT::AAAraghavanvorp_damageType::Instance().Name() << " "
    << MAT::AAA_mixedeffectsType::Instance().Name() << " "
    << MAT::ArrheniusPVType::Instance().Name() << " " << MAT::ArrheniusSpecType::Instance().Name()
    << " " << MAT::ArrheniusTempType::Instance().Name() << " "
    << MAT::CarreauYasudaType::Instance().Name() << " "
    << MAT::ConstraintMixtureType::Instance().Name() << " "
    << MAT::ConstraintMixtureHistoryType::Instance().Name() << " "
    << MAT::CrystalPlasticityType::Instance().Name() << " "
    << MAT::ElastHyperType::Instance().Name() << " "
    << MAT::PlasticElastHyperType::Instance().Name() << " "
    << MAT::PlasticElastHyperVCUType::Instance().Name() << " "
    << MAT::ViscoElastHyperType::Instance().Name() << " " << MAT::FerEchPVType::Instance().Name()
    << " " << MAT::FluidPoroType::Instance().Name() << " "
    << MAT::FluidPoroSinglePhaseType::Instance().Name() << " "
    << MAT::FluidPoroSingleVolFracType::Instance().Name() << " "
    << MAT::FluidPoroVolFracPressureType::Instance().Name() << " "
    << MAT::FluidPoroSingleReactionType::Instance().Name() << " "
    << MAT::FluidPoroMultiPhaseType::Instance().Name() << " "
    << MAT::FluidPoroMultiPhaseReactionsType::Instance().Name() << " "
    << MAT::FourierIsoType::Instance().Name() << " " << MAT::GrowthVolumetricType::Instance().Name()
    << " " << MAT::Membrane_ElastHyperType::Instance().Name() << " "
    << MAT::Membrane_ActiveStrainType::Instance().Name() << " "
    << MAT::GrowthRemodel_ElastHyperType::Instance().Name() << " "
    << MAT::Mixture_ElastHyperType::Instance().Name() << " "
    << MAT::HerschelBulkleyType::Instance().Name() << " " << MAT::IonType::Instance().Name() << " "
    << MAT::LinearDensityViscosityType::Instance().Name() << " "
    << MAT::WeaklyCompressibleFluidType::Instance().Name() << " "
    << MAT::MatListType::Instance().Name() << " " << MAT::MatListReactionsType::Instance().Name()
    << " " << MAT::MatListChemotaxisType::Instance().Name() << " "
    << MAT::MatListChemoReacType::Instance().Name() << " " << MAT::ElchMatType::Instance().Name()
    << " " << MAT::MicroMaterialType::Instance().Name() << " "
    << MAT::MixFracType::Instance().Name() << " " << MAT::ModPowerLawType::Instance().Name() << " "
    << MAT::MurnaghanTaitFluidType::Instance().Name() << " " << MAT::MyocardType::Instance().Name()
    << MAT::NewtonianFluidType::Instance().Name() << " " << MAT::StructPoroType::Instance().Name()
    << " " << MAT::StructPoroReactionType::Instance().Name() << " "
    << MAT::StructPoroReactionECMType::Instance().Name() << " "
    << MAT::ScalarDepInterpType::Instance().Name() << " " << MAT::ScatraMatType::Instance().Name()
    << " " << MAT::ScatraMatPoroECMType::Instance().Name() << " "
    << MAT::ScatraMatMultiPoroFluidType::Instance().Name() << " "
    << MAT::ScatraMatMultiPoroVolFracType::Instance().Name() << " "
    << MAT::ScatraMatMultiPoroSolidType::Instance().Name() << " "
    << MAT::ScatraMatMultiPoroTemperatureType::Instance().Name() << " "
    << MAT::StVenantKirchhoffType::Instance().Name() << " "
    << MAT::LinElast1DType::Instance().Name() << " " << MAT::LinElast1DGrowthType::Instance().Name()
    << " " << MAT::SutherlandType::Instance().Name() << " "
    << MAT::TempDepWaterType::Instance().Name() << " "
    << MAT::ThermoStVenantKirchhoffType::Instance().Name() << " "
    << MAT::ThermoPlasticLinElastType::Instance().Name() << " "
    << MAT::ViscoAnisotropicType::Instance().Name() << " "
    << MAT::ViscoNeoHookeType::Instance().Name() << " " << MAT::YoghurtType::Instance().Name()
    << " " << MAT::SpringType::Instance().Name() << " "
    << MAT::BeamElastHyperMaterialType<double>::Instance().Name() << " "
    << MAT::BeamElastHyperMaterialType<Sacado::Fad::DFad<double>>::Instance().Name() << " "
    << MAT::PlasticLinElastType::Instance().Name() << " " << MAT::RobinsonType::Instance().Name()
    << " " << MAT::DamageType::Instance().Name() << " " << MAT::TopOptDensType::Instance().Name()
    << MAT::ElectromagneticMatType::Instance().Name() << " "
    << MAT::Maxwell_0d_acinusType::Instance().Name() << " "
    << MAT::Maxwell_0d_acinusNeoHookeanType::Instance().Name() << " "
    << MAT::Maxwell_0d_acinusExponentialType::Instance().Name() << " "
    << MAT::Maxwell_0d_acinusDoubleExponentialType::Instance().Name() << " "
    << MAT::Maxwell_0d_acinusOgdenType::Instance().Name() << " "
    << MORTAR::MortarNodeType::Instance().Name() << " "
    << MORTAR::MortarElementType::Instance().Name() << " " << CONTACT::CoNodeType::Instance().Name()
    << " " << CONTACT::FriNodeType::Instance().Name() << " "
    << CONTACT::CoElementType::Instance().Name() << " " << MAT::ActiveFiberType::Instance().Name()
    << INVANA::ParticleDataType::Instance().Name() << " "
    << BEAMINTERACTION::BeamLinkBeam3rLine2RigidJointedType::Instance().Name() << " "
    << BEAMINTERACTION::BeamLinkBeam3rLine2PinJointedType::Instance().Name() << " "
    << BEAMINTERACTION::BeamLinkTrussType::Instance().Name() << " "
    << PARTICLEENGINE::ParticleObjectType::Instance().Name() << " ";

  std::cout << s.str() << std::endl;
  return s.str();
}


void PrintParObjectList()
{
  std::cout << "Here are all defined DRT::ParObject types: " << DRT::ParObjectList() << "\n";
}
