
all: post_visual2 post_visual3

post_visual2:
	cd ../.. && $(MAKE) post_visual2

post_visual3:
	cd ../.. && $(MAKE) post_visual3

post_file_manager:
	cd ../.. && $(MAKE) post_file_manager

clean:
	cd ../.. && $(MAKE) clean
