/*----------------------------------------------------------------------*/
/*! \file

\brief global algorithm control class for all immersed algorithms

\level 2


*----------------------------------------------------------------------*/
#ifndef IMMERSED_PROBLEM_DYN_H
#define IMMERSED_PROBLEM_DYN_H

//! global immersed fsi algorithm.
void immersed_problem_drt();

/*----------------------------------------------------------------------*/
#endif /* #ifndef IMMERSED_PROBLEM_DYN_H*/
