// This file is part of 4C multiphysics licensed under the
// GNU Lesser General Public License v3.0 or later.
//
// See the LICENSE.md file in the top-level for license information.
//
// SPDX-License-Identifier: LGPL-3.0-or-later

#ifndef FOUR_C_FEM_CONDITION_PERIODIC_HPP
#define FOUR_C_FEM_CONDITION_PERIODIC_HPP

#include "4C_config.hpp"

#include "4C_fem_condition.hpp"
#include "4C_linalg_map.hpp"

#include <Teuchos_Time.hpp>
#include <Teuchos_TimeMonitor.hpp>

#include <memory>

FOUR_C_NAMESPACE_OPEN

namespace Core::FE
{
  class Discretization;
}  // namespace Core::FE

namespace Core::DOFSets
{
  class PBCDofSet;
}  // namespace Core::DOFSets


namespace Core::Conditions
{
  /*!
  \brief  update dofrowmap and dofsets for periodic boundary conditions

          o effects distribution of target and source nodes. Target and
            source are owned by one proc afterwards.

          o effects ghosting of nodes. Target and source nodes are ghosted
            in pairs.

          o passes list of coupled nodes to the dofset

  */
  class PeriodicBoundaryConditions
  {
   public:
    /*!
    \brief Standard Constructor

    This method gets the periodic boundary conditions from the discretisation
    and creates some empty maps which will be filled by the node matching.


    \param  dis (i) Discretisation which contains the nodes of the
                    periodic boundary condition


    \return void

    */
    PeriodicBoundaryConditions(std::shared_ptr<Core::FE::Discretization> dis, bool verbose = true);

    /*!
    \brief Destructor

    */
    virtual ~PeriodicBoundaryConditions() = default;

    //! @name Framework

    /*!
      \brief This method gathers all source nodes on the target node's
      proc, eliminates their dofs and redistributes (nodes and
      target/source couples) afterwards to get a better distribution
      of dofs among processors.

      After this function, the nodes and elements are redistributed among
      the processors according to the generated connectivity. During this
      procedure, the dof set is changed (coupled dofs are eliminated)
      and the dofs are renumbered.

    \return void

    */
    void update_dofs_for_periodic_boundary_conditions();
    //@}

    //! @name methods to provide constructed node to node coupling
    std::shared_ptr<std::map<int, std::vector<int>>> return_all_coupled_col_nodes()
    {
      return (allcoupledcolnodes_);
    }
    //@}

    //! @name methods to provide constructed node to node coupling
    std::shared_ptr<std::map<int, std::vector<int>>> return_all_coupled_row_nodes()
    {
      return (allcoupledrownodes_);
    }
    //@}


    bool has_pbc()
    {
      if (numpbcpairs_ > 0)
      {
        return (true);
      }
      else
      {
        return (false);
      }
    }

    //@}


    //! @name handling of all pbc pairs

    /*!
    \brief generate maps of target->source couples and send the sources
    to the target's proc. Update the dofset.

     o generate target->source connectivities
        * allcoupledrownodes_
        * allcoupledcolnodes_ (including ghosted target/source nodes)

        This method contains a loop over all existing pairs of
        periodic boundary conditions (always two surfaces (3d) or lines
        (2d) belong to the same condition. They are usually referred to
        as corresponding "target" and "source" conditions).

        For every pair a node coupling is generated by a call to the
        method create_node_coupling_for_single_pbc. This means, that we have
        the information which targetnode id is coupled to which
        sourcenode id (map midtosid).

        This node coupling is added to the connectivity map of all
        previous periodic boundary conditions (this allows pbcs in
        several spatial directions which are necessary for example
        for 3d channel flows).

     o send source nodes to target proc.

     o Generate a new dofset in which sources do not have their own dofs
       anymore; they just point to the target's dofs

       After this function call, the nodes and elements are distributed
       among the processors according to the generated connectivity.
       During this procedure, the dof set is changed (coupled dofs are
       eliminated) and the dofs are renumbered.

       \return void

    */
    void put_all_sources_to_targets_proc();

   protected:
    /*!
    \brief Couple nodes for specific pair of periodic boundary conditions.

    On input, this method needs two lists of nodes (target- and
    sourcenodes). For every targetnode, the method will look for the
    "closest" sourcenode and insert this connectivity in the midtosid map.
    In this context, "closest" means, that one coordinate of the sourcenode
    is replaced by the coordinate of the targetnode plane for the search
    of the closest point. This is controlled by the parameter dofsforpbcplane,
    an int vector of length 3:


                       (1,1,0)    xy-plane

                       (0,1,1)    yz-plane

                       (1,0,1)    xz-plane

    The search algorithm will substitute the coordinate with 0 of the
    sourcenodes by the corresponding coordinate of the targetnode plane
    to calculate the closest node.

    Keep in mind that the targetnodes and the sourcenodes are distributed
    among several processors. The connectivity information will be only
    available on the proc which owns the specific targetnode --- but the
    corresponding closest sourcenode will be searched on all procs!

    The node matching is created in two steps. Step one generates a
    processor local octree that contains all targetnodes available on
    this proc (NodeMatchingOctree nodematchingoctree).
    The second part searches for the closest source node on
    all processors (nodematchingoctree.CreateGlobalNodeMatching).


    \param  midtosid        (o) map from target to sourcenodes
    \param  targetnodeids   (i) all target node ids
    \param  sourcenodeids    (i) all source node ids
    \param  dofsforpbcplane (i) periodic boundary is in this plane
    \param  rotangle        (i) angle (RAD) for rotation of source plane
    \return void

    */
    void create_node_coupling_for_single_pbc(std::map<int, std::vector<int>>& midtosid,
        const std::vector<int> targetnodeids, const std::vector<int> sourcenodeids,
        const std::vector<int> dofsforpbcplane, const double rotangle, const double abstol);

    /*!
    \brief Add the connectivity from this condition (midtosid, on input)
    to the connectivity of all previously processed periodic boundary
    conditions (allcoupledrownodes_).

    We are interested in a map of all coupled nodes. For nodes, which have
    several periodic boundary conditions (for example edge nodes for
    3d channel flow, see figure below), only one node (the pure target node)
    is allowed to have its own degrees of freedom. The mixed target/source
    nodes must be eliminated and all connectivity information must be
    transferred to the pure target.

          MM----------MS

           |xxxxxxxxxx|

           |xxxxxxxxxx|

           |xxxxxxxxxx|

          SM----------SS

    Since not all information is available on every proc, the completion
    of this coupling requires some additional communication of the coupling
    behaviour of multiple coupled nodes.


    \param  midtosid        (i) map from target to sourcenodes of current condition
    \param  pbcid           (i) the id of the current periodic boundary condition

    \return void

    */
    void add_connectivity(std::map<int, std::vector<int>>& midtosid, const int pbcid);

    //@}


    //! @name Methods to finish the coupling after the list of coupled nodes is known.

    /*!
    \brief Redistribute the nodes and assign the dofs to the
    current distribution of nodes

    o Create a new rownodemap using the map allcoupledrownodes_

    o Build graph and temporary nodecolmap

    o Fix ghosting (if sources are ghosted, targetnodes have to
      be ghosted, too)
      This leads to the newnodecolmap

    o Create a new dofset specialisation for periodic boundary
      conditions

    o Redistribute nodes and call FillComplete including a call
      to the modified AssignDegreesOfFreedom

    \return void

    */
    void redistribute_and_create_dof_coupling();

    //@}

    /*!
    \brief generate a better distribution of nodes for more efficiency in a parallel setting

     o adjust weights of sourcenodes they need a small weight since they do not contribute any dofs
       to the linear system

     o compute connectivity iterate all elements on this proc including ghosted ones. Include
       additional connections between target and source nodes

     o set weights of edges between target/source pairs to a high value
       in order to keep both on the same proc when redistributing

     o gather all data to proc 1, do partitioning using METIS with both, weights for edges and nodes

     o redistribute nodes without assigning dofs

     o repair target/source distribution, finally assign dofs
    */
    void balance_load();

    //@}

    //!\brief the discretisation
    std::shared_ptr<Core::FE::Discretization> discret_;

    //!\brief a flag controlling the verbosity, i.e. the amount of output
    // displayed on the screen
    bool verbose_;

    //!\brief the pbc-dofset created by this object
    std::shared_ptr<Core::DOFSets::PBCDofSet> pbcdofset_;

    //!\brief number of pairs of periodic boundary conditions
    int numpbcpairs_;

    //!\brief vector of periodic surface boundary conditions
    std::vector<const Core::Conditions::Condition*> mysurfpbcs_;

    //!\brief map connecting target to source nodes owned by this proc
    //       target node -> list of its source node(s)
    std::shared_ptr<std::map<int, std::vector<int>>> allcoupledrownodes_;

    //!\brief map connecting target to source nodes owned or ghosted by this proc
    //       target node -> list of its source node(s)
    std::shared_ptr<std::map<int, std::vector<int>>> allcoupledcolnodes_;
  };
}  // namespace Core::Conditions

FOUR_C_NAMESPACE_CLOSE

#endif
