/*---------------------------------------------------------------------*/
/*! \file
\brief Control routine for structural dynamics (outsourced to adapter layer)


\level 1
*/
/*---------------------------------------------------------------------*/

#ifndef BACI_STRUCTURE_DYN_NLN_DRT_H
#define BACI_STRUCTURE_DYN_NLN_DRT_H

#include "baci_config.H"

BACI_NAMESPACE_OPEN


void dyn_nlnstructural_drt();
void caldyn_drt();


BACI_NAMESPACE_CLOSE

#endif  // STRUCTURE_DYN_NLN_DRT_H
