
if (UMFPACK_INCLUDE_DIR AND UMFPACK_LIBRARY)
  set(UMFPACK_FIND_QUIETLY TRUE)
endif (UMFPACK_INCLUDE_DIR AND UMFPACK_LIBRARY)

find_path(UMFPACK_INCLUDE_DIR
  NAMES
  umfpack.h
  PATHS
  $ENV{UMFPACKDIR}
  ${INCLUDE_INSTALL_DIR}
  PATH_SUFFIXES
  suitesparse
  )

find_library(UMFPACK_LIBRARY umfpack PATHS $ENV{UMFPACKDIR} ${LIB_INSTALL_DIR})
find_library(AMD_LIBRARY     amd     PATHS $ENV{UMFPACKDIR} ${LIB_INSTALL_DIR})
mark_as_advanced(UMFPACK_INCLUDE_DIR UMFPACK_LIBRARY AMD_LIBRARY)

#    if(UMFPACK_LIBRARY)

#      find_library(COLAMD_LIBRARY colamd PATHS ${UMFPACK_LIBDIR} $ENV{UMFPACKDIR} ${LIB_INSTALL_DIR})
#      if (COLAMD_LIBRARY)
#        set(UMFPACK_LIBRARY ${UMFPACK_LIBRARY} ${COLAMD_LIBRARY})
#        #else (COLAMD_LIBRARY)
#        #  set(UMFPACK_LIBRARY FALSE)
#      endif (COLAMD_LIBRARY)

#    endif(UMFPACK_LIBRARY)

# Per-recommendation
SET( UMFPACK_INCLUDE_DIRS ${UMFPACK_INCLUDE_DIR})
SET( UMFPACK_LIBRARIES    ${UMFPACK_LIBRARY} ${AMD_LIBRARY} ${COLAMD_LIBRARY} ${BLAS_LIBRARIES})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(UMFPACK DEFAULT_MSG UMFPACK_LIBRARIES UMFPACK_INCLUDE_DIRS)
