/*!----------------------------------------------------------------------
\file wear_dyn.H
\brief Control routine for structure with ale problems (wear).


<pre>
Maintainer: Philipp Farah
            farah@lnm.mw.tum.de
            http://www.lnm.mw.tum.de
            089 - 289-15257
</pre>

*----------------------------------------------------------------------*/

#ifndef WEAR_DYN_H
#define WEAR_DYN_H

/* entry point for the solution of structural ale wear problems */
void wear_dyn_drt(int restart);

/*----------------------------------------------------------------------*/
#endif /* #ifndef WEAR_DYN_H */
