/*
 * str_impl_genalpha.H
 *
 *  Created on: Aug 13, 2015
 *      Author: farah
 */

#ifndef STR_IMPL_GENALPHA_H_
#define STR_IMPL_GENALPHA_H_

#include "str_impl_generic.H"

namespace STR {
namespace IMPLICIT {
  class GenAlpha : public Generic
  {
  public:

    //! constructor
    GenAlpha();

    //! destructor
    virtual ~GenAlpha() {};
  };
} // namespace IMPLICIT
} // namespace STR


#endif /* STR_IMPL_GENALPHA_H_ */
