#!/bin/bash

# set the field separator to new line
IFS=$'\n'

# test all changed files
for line in "$@"
do
# check if there are non-ascii characters in the file (excluding *.md files)
  non_ascii_chars=`(git diff HEAD $line | grep --perl-regex --no-filename --only-matching --binary-files=without-match "[^\x00-\x7F]" | sort --unique | tr --delete '\n')`
  if [ -n "$non_ascii_chars" ]; then
    cnt=${#non_ascii_chars}
    for ((i=0; i < cnt; i++)); do
      char=${non_ascii_chars:$i:1}
      non_ascii_error+="${line} contains non-ascii character '$char'\n"
    done
  fi
done

# printout for non-ascii characters
if [ ! -z "$non_ascii_error" ]
then
printf "\n"
printf "The following file(s) contain non-ascii characters:\n"
printf "\n"
echo "########################################################################"
printf $non_ascii_error
echo "########################################################################"
printf "\n"
echo "--> Please remove those non-ascii characters"
fi

exit 0
