#!/bin/bash

#####################################################
########## DESCRIPTION ##############################
#####################################################

# This is a bash script meant for code checks concerning clang-format style and header compliance.

# The test will fail if code is found that is not compliant with the BACI clang format style.
# In this preliminary version uncompliant headers will not lead to a test failure but the affected files will be written out in a text file called "wrong_headers_or_supportfiles.txt"
# This ensures that the work with BACI is not interrupted and gives time to work on non-compliant headers, in parallel.
# The files with non-compliant code format will also be written out in a file named "wrong_clang_format.txt"

# Author:    Jonas Nitzler
# Date:      07.08.2019
# Version:   1.1

## Delete old .txt files containing non-compliant files
[ -e wrong_clang_format.txt ] && rm wrong_clang_format.txt
########### Execute clang-format with style file settings (taken from https://github.com/sheredom/git-hooks)##################################################
if [ -f ./utilities/code_checks/clang-format ]
then
  # set the field separator to new line
  IFS=$'\n'

  echo "Start test for code format ..."
  for line in $(find ./ -type f)
  do
    # check if the file is a c or cpp file
    if [[ $line == *.cpp || $line == *.cc || $line == *.cp || $line == *.cxx || $line == *.H || $line == *.h || $line == *.hpp || $line == *.hh || $line == *.hxx ]]
    then
      # Check if clang would format the file
      ./utilities/code_checks/clang-format -i -style=file $(pwd)/${line}
    fi
  done
fi

