name: documentation

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 22 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doxygen:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4c-multiphysics/4c-dependencies-ubuntu24.04:24b228a5
      options: --user root --env OMPI_ALLOW_RUN_AS_ROOT=1 --env OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - name: Check docker hash
        uses: ./.github/actions/compute-and-check-dependencies-hash
      - uses: ./.github/actions/build_4C
        with:
          cmake-preset: docker
          build-targets: doxygen
          build-directory: ${{ github.workspace }}/build
          use-ccache: "false"
          additional-cmake-flags: -DFOUR_C_ENABLE_DOXYGEN="ON"
      - name: Upload doxygen
        uses: actions/upload-artifact@v7
        with:
          name: doxygen
          path: ${{ github.workspace }}/build/doc/doxygen/html/
          retention-days: 2

  documentation:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4c-multiphysics/4c-dependencies-ubuntu24.04:24b228a5
      options: --user root --env OMPI_ALLOW_RUN_AS_ROOT=1 --env OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - name: Check docker hash
        uses: ./.github/actions/compute-and-check-dependencies-hash
      - uses: ./.github/actions/build_4C
        with:
          cmake-preset: docker
          build-targets: documentation
          build-directory: ${{ github.workspace }}/build
          use-ccache: "true"
      - name: Upload documentation
        uses: actions/upload-artifact@v7
        with:
          name: documentation
          path: ${{ github.workspace }}/build/doc/documentation/html/
          retention-days: 2
