name: Windows build test

on:
  schedule:
    - cron: 3 4 * * 0
      timezone: "Europe/Berlin"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build 4C on Windows
    runs-on: windows-latest
    outputs:
      msvc-version-hash: ${{ steps.msvc-version.outputs.hash }}

    steps:
      - uses: actions/checkout@v7
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Intel Fortran
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: intel
          version: "2026.1"

      - name: Verify Intel Fortran
        shell: pwsh
        run: |
          ifx --version
          Write-Host "FC=$env:FC"
          Write-Host "CC=$env:CC"
          Write-Host "CXX=$env:CXX"

      - name: System preparation
        shell: pwsh
        run: |
          ./dependencies/windows/prepare_system.ps1

      - name: Get MSVC version
        id: msvc-version
        shell: pwsh
        run: |
          $version = cl 2>&1 | Select-Object -First 1
          Write-Host "MSVC: $version"

          $hash = [System.BitConverter]::ToString(
            [System.Security.Cryptography.SHA256]::HashData(
              [System.Text.Encoding]::UTF8.GetBytes($version)
            )
          ).Replace("-", "").ToLower()

          "hash=$hash" >> $env:GITHUB_OUTPUT

      - name: Restore dependencies cache
        id: cache-deps
        uses: actions/cache/restore@v6
        with:
          path: ${{ env.USERPROFILE }}/opt
          key: ${{ runner.os }}-deps-${{ hashFiles('./dependencies/windows/compile_dependencies.ps1',
            './dependencies/windows/**/install.ps1') }}-msvc-${{ steps.msvc-version.outputs.hash }}

      - name: Compile and install the dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Write-Host "Install the dependencies"
          ./dependencies/windows/compile_dependencies.ps1

      - name: Save dependencies cache
        if: success() && steps.cache-deps.outputs.cache-hit != 'true'
        uses: actions/cache/save@v6
        with:
          path: ${{ env.USERPROFILE }}/opt
          key: ${{ runner.os }}-deps-${{ hashFiles('./dependencies/windows/compile_dependencies.ps1',
            './dependencies/windows/**/install.ps1') }}-msvc-${{ steps.msvc-version.outputs.hash }}

    # - name: Restore build cache
    #   id: cache-build
    #   uses: actions/cache/restore@v6
    #   with:
    #     path: build/
    #     key: ${{ runner.os }}-build-${{ github.sha }}-msvc-${{ steps.msvc-version.outputs.hash }}

    # - name: Build 4C
    #   if: steps.cache-build.outputs.cache-hit != 'true'
    #   shell: pwsh
    #   run: |
    #     Get-Location
    #     cmake -B build/ --fresh --preset=cl_release
    #     cmake --build build/ --target full --config Release

    # - name: Save build cache
    #   if: success() && steps.cache-build.outputs.cache-hit != 'true'
    #   uses: actions/cache/save@v6
    #   with:
    #     path: build/
    #     key: ${{ runner.os }}-build-${{ github.sha }}-msvc-${{ steps.msvc-version.outputs.hash }}

# test:
#   name: Test 4C on Windows
#   needs: build
#   runs-on: windows-latest

#   steps:
#     - uses: actions/checkout@v7

#     - name: Set up MSVC
#       uses: ilammy/msvc-dev-cmd@v1

#     - name: System preparation
#       shell: pwsh
#       run: |
#         ./dependencies/windows/prepare_system.ps1

#     - name: Get MSVC version
#       id: msvc-version
#       shell: pwsh
#       run: |
#         $version = cl 2>&1 | Select-Object -First 1
#         Write-Host "MSVC: $version"

#         $hash = [System.BitConverter]::ToString(
#           [System.Security.Cryptography.SHA256]::HashData(
#             [System.Text.Encoding]::UTF8.GetBytes($version)
#           )
#         ).Replace("-", "").ToLower()

#         "hash=$hash" >> $env:GITHUB_OUTPUT

#     - name: Check if the compiler differs from the build job
#       if: steps.msvc-version.outputs.hash != needs.build.outputs.msvc-version-hash
#       shell: pwsh
#       run: |
#         @"
#         ### Changed MSVC version!

#         The test job aborted because the MSVC compiler version changed
#         after the build job completed.

#         The compiler used by the test job is different from the one
#         used to build 4C.

#         This should rarely happen. A re-run of the workflow should
#         solve this problem.
#         "@ >> $env:GITHUB_STEP_SUMMARY

#         exit 1

#     - name: Restore dependencies cache
#       id: cache-deps
#       uses: actions/cache/restore@v6
#       with:
#         path: ${{ env.USERPROFILE }}/opt
#         key: ${{ runner.os }}-deps-${{ hashFiles('./dependencies/windows/compile_dependencies.ps1',
#           'dependencies/windows/**/install.ps1') }}-msvc-${{ steps.msvc-version.outputs.hash }}

#     - name: Restore build cache
#       id: cache-build
#       uses: actions/cache/restore@v6
#       with:
#         path: build/
#         key: ${{ runner.os }}-build-${{ github.sha }}-msvc-${{ steps.msvc-version.outputs.hash }}

#     - name: Run tests
#       shell: pwsh
#       run: |
#         Write-Host "Running tests"

#         $jobs = [Environment]::ProcessorCount

#         ctest `
#           --test-dir build/ `
#           --build-config Release `
#           -j $jobs `
#           --output-on-failure `
#           --output-junit "$env:GITHUB_WORKSPACE/windows_assertions_test_report.xml"

#     - name: Upload test report
#       if: success() || failure()
#       uses: actions/upload-artifact@v7
#       with:
#         name: windows_assertions_test_report.xml
#         path: |
#           ${{ github.workspace }}/windows_assertions_test_report.xml
